"""
server_handlers.py — AUTO-GENERATED by codegen.py. Do not edit directly.
Re-generate by running: python codegen.py schema.json --out-dir <dir>

Contains:
  HANDLERS  dict[str, Callable] mapping "ClassName.method" → handler fn
  Each handler signature: fn(session_id, registry, params) -> result
"""

from __future__ import annotations
import sys
from typing import TYPE_CHECKING, Any, Callable
from functools import wraps
from dataclasses import dataclass
import numpy as np

try:
    from Swabian import TimeTagger as TT
except ImportError:
    import TimeTagger as TT


@dataclass
class HandlerContext:
    session_id: int
    registry: dict
    sessions: dict


if TYPE_CHECKING:
    if sys.version_info >= (3, 12):
        type SwabianFn = Callable[[HandlerContext, Any], Any]
    else:
        from typing import TypeAlias
        SwabianFn: TypeAlias = Callable[[HandlerContext, Any], Any]

HANDLERS: dict[str, SwabianFn] = {}

def handler(name: str):
    def decorator(func: SwabianFn):
        @wraps(func)
        def wrapper(*args: Any, **kwargs: Any) -> Any:
            return func(*args, **kwargs)

        HANDLERS[name] = wrapper
        return wrapper
    return decorator


def _lookup(registry: dict, handle_id: int):
    entry = registry.get(handle_id)
    if entry is None:
        raise KeyError(f"Unknown handle: {handle_id}")
    return entry["obj"]

def _register(obj, class_name: str, session_id: int, registry: dict, sessions: dict) -> int:
    import itertools
    handle_id = next(registry["_counter"])
    registry[handle_id] = {"obj": obj, "class_name": class_name,
                           "session_id": session_id}
    sessions.setdefault(session_id, set()).add(handle_id)
    return handle_id

# numpy array needs to be marshalled
def _pack_ndarray(arr) -> dict:
    import io
    buf = io.BytesIO()
    np.save(buf, arr, allow_pickle=False)
    return {"dtype": str(arr.dtype),
            "shape": list(arr.shape),
            "data": buf.getvalue()}


# Module-level functions

@handler("getVersion")
def _fn_getVersion(ctx: HandlerContext, params):
    _ = params
    _ = ctx
    return TT.getVersion()

@handler("getCompilerVersion")
def _fn_getCompilerVersion(ctx: HandlerContext, params):
    _ = params
    _ = ctx
    return TT.getCompilerVersion()

@handler("getCompilationTimestamp")
def _fn_getCompilationTimestamp(ctx: HandlerContext, params):
    _ = params
    _ = ctx
    return TT.getCompilationTimestamp()

@handler("createTimeTagger")
def _fn_createTimeTagger(ctx: HandlerContext, params):
    obj = TT.createTimeTagger(*params)
    return _register(obj, 'TimeTagger', ctx.session_id, ctx.registry, ctx.sessions)

@handler("createTimeTaggerVirtual")
def _fn_createTimeTaggerVirtual(ctx: HandlerContext, params):
    obj = TT.createTimeTaggerVirtual(*params)
    return _register(obj, 'TimeTaggerVirtual', ctx.session_id, ctx.registry, ctx.sessions)

@handler("createTimeTaggerNetwork")
def _fn_createTimeTaggerNetwork(ctx: HandlerContext, params):
    obj = TT.createTimeTaggerNetwork(*params)
    return _register(obj, 'TimeTaggerNetwork', ctx.session_id, ctx.registry, ctx.sessions)

@handler("setCustomBitFileName")
def _fn_setCustomBitFileName(ctx: HandlerContext, params):
    _ = ctx
    return TT.setCustomBitFileName(params[0])

@handler("scanTimeTagger")
def _fn_scanTimeTagger(ctx: HandlerContext, params):
    _ = ctx
    return TT.scanTimeTagger(params[0])

@handler("getTimeTaggerServerInfo")
def _fn_getTimeTaggerServerInfo(ctx: HandlerContext, params):
    _ = ctx
    return TT.getTimeTaggerServerInfo(*params)

@handler("scanTimeTaggerServers")
def _fn_scanTimeTaggerServers(ctx: HandlerContext, params):
    _ = params
    _ = ctx
    return TT.scanTimeTaggerServers()

@handler("getTimeTaggerModel")
def _fn_getTimeTaggerModel(ctx: HandlerContext, params):
    _ = ctx
    return TT.getTimeTaggerModel(params[0])

@handler("setTimeTaggerChannelNumberScheme")
def _fn_setTimeTaggerChannelNumberScheme(ctx: HandlerContext, params):
    _ = ctx
    return TT.setTimeTaggerChannelNumberScheme(params[0])

@handler("getTimeTaggerChannelNumberScheme")
def _fn_getTimeTaggerChannelNumberScheme(ctx: HandlerContext, params):
    _ = params
    _ = ctx
    return TT.getTimeTaggerChannelNumberScheme()

@handler("hasTimeTaggerVirtualLicense")
def _fn_hasTimeTaggerVirtualLicense(ctx: HandlerContext, params):
    _ = params
    _ = ctx
    return TT.hasTimeTaggerVirtualLicense()

@handler("flashLicense")
def _fn_flashLicense(ctx: HandlerContext, params):
    _ = ctx
    return TT.flashLicense(params[0], params[1])

@handler("extractDeviceLicense")
def _fn_extractDeviceLicense(ctx: HandlerContext, params):
    _ = ctx
    return TT.extractDeviceLicense(params[0])

@handler("checkSystemLibraries")
def _fn_checkSystemLibraries(ctx: HandlerContext, params):
    _ = params
    _ = ctx
    return TT.checkSystemLibraries()

@handler("setLanguageInfo")
def _fn_setLanguageInfo(ctx: HandlerContext, params):
    _ = ctx
    return TT.setLanguageInfo(params[0], _lookup(ctx.registry, params[1]), params[2])

@handler("setFrontend")
def _fn_setFrontend(ctx: HandlerContext, params):
    _ = ctx
    return TT.setFrontend(_lookup(ctx.registry, params[0]))

@handler("setUsageStatisticsStatus")
def _fn_setUsageStatisticsStatus(ctx: HandlerContext, params):
    _ = ctx
    return TT.setUsageStatisticsStatus(_lookup(ctx.registry, params[0]))

@handler("getUsageStatisticsStatus")
def _fn_getUsageStatisticsStatus(ctx: HandlerContext, params):
    _ = params
    _ = ctx
    return TT.getUsageStatisticsStatus()

@handler("getUsageStatisticsReport")
def _fn_getUsageStatisticsReport(ctx: HandlerContext, params):
    _ = params
    _ = ctx
    return TT.getUsageStatisticsReport()

@handler("mergeStreamFiles")
def _fn_mergeStreamFiles(ctx: HandlerContext, params):
    _ = ctx
    return TT.mergeStreamFiles(params[0], params[1], params[2], params[3], params[4])

@handler("freeTimeTagger")
def _fn_freeTimeTagger(ctx: HandlerContext, params):
    _ = ctx
    return TT.freeTimeTagger(_lookup(ctx.registry, params[0]))

# Class constructors

@handler("TimeTaggerSource")
def _ctor_TimeTaggerSource(ctx: HandlerContext, params):
    obj = TT.TimeTaggerSource(*params)
    return _register(obj, 'TimeTaggerSource', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeTaggerBase")
def _ctor_TimeTaggerBase(ctx: HandlerContext, params):
    obj = TT.TimeTaggerBase(*params)
    return _register(obj, 'TimeTaggerBase', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeTaggerHardware")
def _ctor_TimeTaggerHardware(ctx: HandlerContext, params):
    obj = TT.TimeTaggerHardware(*params)
    return _register(obj, 'TimeTaggerHardware', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeTaggerServer")
def _ctor_TimeTaggerServer(ctx: HandlerContext, params):
    obj = TT.TimeTaggerServer(*params)
    return _register(obj, 'TimeTaggerServer', ctx.session_id, ctx.registry, ctx.sessions)

@handler("ChannelGate")
def _ctor_ChannelGate(ctx: HandlerContext, params):
    obj = TT.ChannelGate(*params)
    return _register(obj, 'ChannelGate', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Coincidences")
def _ctor_Coincidences(ctx: HandlerContext, params):
    obj = TT.Coincidences(*params)
    return _register(obj, 'Coincidences', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Coincidence")
def _ctor_Coincidence(ctx: HandlerContext, params):
    obj = TT.Coincidence(*params)
    return _register(obj, 'Coincidence', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Combinations")
def _ctor_Combinations(ctx: HandlerContext, params):
    obj = TT.Combinations(_lookup(ctx.registry, params[0]), params[1], params[2])
    return _register(obj, 'Combinations', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Combiner")
def _ctor_Combiner(ctx: HandlerContext, params):
    obj = TT.Combiner(_lookup(ctx.registry, params[0]), params[1])
    return _register(obj, 'Combiner', ctx.session_id, ctx.registry, ctx.sessions)

@handler("ConditionalFilterChannel")
def _ctor_ConditionalFilterChannel(ctx: HandlerContext, params):
    obj = TT.ConditionalFilterChannel(*params)
    return _register(obj, 'ConditionalFilterChannel', ctx.session_id, ctx.registry, ctx.sessions)

@handler("ConstantFractionDiscriminator")
def _ctor_ConstantFractionDiscriminator(ctx: HandlerContext, params):
    obj = TT.ConstantFractionDiscriminator(_lookup(ctx.registry, params[0]), params[1], params[2])
    return _register(obj, 'ConstantFractionDiscriminator', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Correlation")
def _ctor_Correlation(ctx: HandlerContext, params):
    obj = TT.Correlation(*params)
    return _register(obj, 'Correlation', ctx.session_id, ctx.registry, ctx.sessions)

@handler("CorrelationPairsData")
def _ctor_CorrelationPairsData(ctx: HandlerContext, params):
    obj = TT.CorrelationPairsData(*params)
    return _register(obj, 'CorrelationPairsData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("CorrelationPairs")
def _ctor_CorrelationPairs(ctx: HandlerContext, params):
    obj = TT.CorrelationPairs(_lookup(ctx.registry, params[0]), params[1], params[2], params[3])
    return _register(obj, 'CorrelationPairs', ctx.session_id, ctx.registry, ctx.sessions)

@handler("CountBetweenMarkers")
def _ctor_CountBetweenMarkers(ctx: HandlerContext, params):
    obj = TT.CountBetweenMarkers(*params)
    return _register(obj, 'CountBetweenMarkers', ctx.session_id, ctx.registry, ctx.sessions)

@handler("CounterData")
def _ctor_CounterData(ctx: HandlerContext, params):
    obj = TT.CounterData(*params)
    return _register(obj, 'CounterData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Counter")
def _ctor_Counter(ctx: HandlerContext, params):
    obj = TT.Counter(_lookup(ctx.registry, params[0]), params[1], params[2], params[3])
    return _register(obj, 'Counter', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Countrate")
def _ctor_Countrate(ctx: HandlerContext, params):
    obj = TT.Countrate(_lookup(ctx.registry, params[0]), params[1])
    return _register(obj, 'Countrate', ctx.session_id, ctx.registry, ctx.sessions)

@handler("DelayedChannels")
def _ctor_DelayedChannels(ctx: HandlerContext, params):
    obj = TT.DelayedChannels(_lookup(ctx.registry, params[0]), params[1], params[2])
    return _register(obj, 'DelayedChannels', ctx.session_id, ctx.registry, ctx.sessions)

@handler("DelayedChannel")
def _ctor_DelayedChannel(ctx: HandlerContext, params):
    obj = TT.DelayedChannel(_lookup(ctx.registry, params[0]), params[1], params[2])
    return _register(obj, 'DelayedChannel', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Dump")
def _ctor_Dump(ctx: HandlerContext, params):
    obj = TT.Dump(*params)
    return _register(obj, 'Dump', ctx.session_id, ctx.registry, ctx.sessions)

@handler("EventGenerator")
def _ctor_EventGenerator(ctx: HandlerContext, params):
    obj = TT.EventGenerator(*params)
    return _register(obj, 'EventGenerator', ctx.session_id, ctx.registry, ctx.sessions)

@handler("FileReader")
def _ctor_FileReader(ctx: HandlerContext, params):
    obj = TT.FileReader(*params)
    return _register(obj, 'FileReader', ctx.session_id, ctx.registry, ctx.sessions)

@handler("FileWriter")
def _ctor_FileWriter(ctx: HandlerContext, params):
    obj = TT.FileWriter(_lookup(ctx.registry, params[0]), params[1], params[2])
    return _register(obj, 'FileWriter', ctx.session_id, ctx.registry, ctx.sessions)

@handler("FlimFrameInfo")
def _ctor_FlimFrameInfo(ctx: HandlerContext, params):
    obj = TT.FlimFrameInfo(*params)
    return _register(obj, 'FlimFrameInfo', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Flim")
def _ctor_Flim(ctx: HandlerContext, params):
    obj = TT.Flim(*params)
    return _register(obj, 'Flim', ctx.session_id, ctx.registry, ctx.sessions)

@handler("FrequencyCounterData")
def _ctor_FrequencyCounterData(ctx: HandlerContext, params):
    obj = TT.FrequencyCounterData(*params)
    return _register(obj, 'FrequencyCounterData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("FrequencyCounter")
def _ctor_FrequencyCounter(ctx: HandlerContext, params):
    obj = TT.FrequencyCounter(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4])
    return _register(obj, 'FrequencyCounter', ctx.session_id, ctx.registry, ctx.sessions)

@handler("FrequencyMultiplier")
def _ctor_FrequencyMultiplier(ctx: HandlerContext, params):
    obj = TT.FrequencyMultiplier(_lookup(ctx.registry, params[0]), params[1], params[2])
    return _register(obj, 'FrequencyMultiplier', ctx.session_id, ctx.registry, ctx.sessions)

@handler("FrequencyStabilityData")
def _ctor_FrequencyStabilityData(ctx: HandlerContext, params):
    obj = TT.FrequencyStabilityData(*params)
    return _register(obj, 'FrequencyStabilityData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("FrequencyStability")
def _ctor_FrequencyStability(ctx: HandlerContext, params):
    obj = TT.FrequencyStability(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4])
    return _register(obj, 'FrequencyStability', ctx.session_id, ctx.registry, ctx.sessions)

@handler("GatedChannel")
def _ctor_GatedChannel(ctx: HandlerContext, params):
    obj = TT.GatedChannel(*params)
    return _register(obj, 'GatedChannel', ctx.session_id, ctx.registry, ctx.sessions)

@handler("HistogramLogBinsData")
def _ctor_HistogramLogBinsData(ctx: HandlerContext, params):
    obj = TT.HistogramLogBinsData(*params)
    return _register(obj, 'HistogramLogBinsData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("HistogramLogBins")
def _ctor_HistogramLogBins(ctx: HandlerContext, params):
    obj = TT.HistogramLogBins(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4], params[5], _lookup(ctx.registry, params[6]), _lookup(ctx.registry, params[7]))
    return _register(obj, 'HistogramLogBins', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Histogram2D")
def _ctor_Histogram2D(ctx: HandlerContext, params):
    obj = TT.Histogram2D(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4], params[5], params[6], params[7])
    return _register(obj, 'Histogram2D', ctx.session_id, ctx.registry, ctx.sessions)

@handler("HistogramND")
def _ctor_HistogramND(ctx: HandlerContext, params):
    obj = TT.HistogramND(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4])
    return _register(obj, 'HistogramND', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_MarkovProcessGenerator")
def _ctor_Experimental_MarkovProcessGenerator(ctx: HandlerContext, params):
    obj = TT.Experimental_MarkovProcessGenerator(*params)
    return _register(obj, 'Experimental_MarkovProcessGenerator', ctx.session_id, ctx.registry, ctx.sessions)

@handler("OverflowInjector")
def _ctor_OverflowInjector(ctx: HandlerContext, params):
    obj = TT.OverflowInjector(_lookup(ctx.registry, params[0]), params[1], params[2])
    return _register(obj, 'OverflowInjector', ctx.session_id, ctx.registry, ctx.sessions)

@handler("PhaseNoiseData")
def _ctor_PhaseNoiseData(ctx: HandlerContext, params):
    obj = TT.PhaseNoiseData(*params)
    return _register(obj, 'PhaseNoiseData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("PhaseNoise")
def _ctor_PhaseNoise(ctx: HandlerContext, params):
    obj = TT.PhaseNoise(_lookup(ctx.registry, params[0]), params[1], params[2])
    return _register(obj, 'PhaseNoise', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_PhotonNumber")
def _ctor_Experimental_PhotonNumber(ctx: HandlerContext, params):
    obj = TT.Experimental_PhotonNumber(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4], params[5], params[6])
    return _register(obj, 'Experimental_PhotonNumber', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_PulsePerSecondData")
def _ctor_Experimental_PulsePerSecondData(ctx: HandlerContext, params):
    obj = TT.Experimental_PulsePerSecondData(*params)
    return _register(obj, 'Experimental_PulsePerSecondData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_PulsePerSecondMonitor")
def _ctor_Experimental_PulsePerSecondMonitor(ctx: HandlerContext, params):
    obj = TT.Experimental_PulsePerSecondMonitor(*params)
    return _register(obj, 'Experimental_PulsePerSecondMonitor', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Sampler")
def _ctor_Sampler(ctx: HandlerContext, params):
    obj = TT.Sampler(_lookup(ctx.registry, params[0]), params[1], params[2], params[3])
    return _register(obj, 'Sampler', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Scope")
def _ctor_Scope(ctx: HandlerContext, params):
    obj = TT.Scope(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4], params[5])
    return _register(obj, 'Scope', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_UniformSignalGenerator")
def _ctor_Experimental_UniformSignalGenerator(ctx: HandlerContext, params):
    obj = TT.Experimental_UniformSignalGenerator(*params)
    return _register(obj, 'Experimental_UniformSignalGenerator', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_GaussianSignalGenerator")
def _ctor_Experimental_GaussianSignalGenerator(ctx: HandlerContext, params):
    obj = TT.Experimental_GaussianSignalGenerator(*params)
    return _register(obj, 'Experimental_GaussianSignalGenerator', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_OscillatorSimulation")
def _ctor_Experimental_OscillatorSimulation(ctx: HandlerContext, params):
    obj = TT.Experimental_OscillatorSimulation(*params)
    return _register(obj, 'Experimental_OscillatorSimulation', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_TwoStateExponentialSignalGenerator")
def _ctor_Experimental_TwoStateExponentialSignalGenerator(ctx: HandlerContext, params):
    obj = TT.Experimental_TwoStateExponentialSignalGenerator(*params)
    return _register(obj, 'Experimental_TwoStateExponentialSignalGenerator', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_ExponentialSignalGenerator")
def _ctor_Experimental_ExponentialSignalGenerator(ctx: HandlerContext, params):
    obj = TT.Experimental_ExponentialSignalGenerator(*params)
    return _register(obj, 'Experimental_ExponentialSignalGenerator', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_GammaSignalGenerator")
def _ctor_Experimental_GammaSignalGenerator(ctx: HandlerContext, params):
    obj = TT.Experimental_GammaSignalGenerator(*params)
    return _register(obj, 'Experimental_GammaSignalGenerator', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_PatternSignalGenerator")
def _ctor_Experimental_PatternSignalGenerator(ctx: HandlerContext, params):
    obj = TT.Experimental_PatternSignalGenerator(*params)
    return _register(obj, 'Experimental_PatternSignalGenerator', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_SimSignalSplitter")
def _ctor_Experimental_SimSignalSplitter(ctx: HandlerContext, params):
    obj = TT.Experimental_SimSignalSplitter(_lookup(ctx.registry, params[0]), params[1], params[2], params[3])
    return _register(obj, 'Experimental_SimSignalSplitter', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_TransformEfficiency")
def _ctor_Experimental_TransformEfficiency(ctx: HandlerContext, params):
    obj = TT.Experimental_TransformEfficiency(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4])
    return _register(obj, 'Experimental_TransformEfficiency', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_TransformGaussianBroadening")
def _ctor_Experimental_TransformGaussianBroadening(ctx: HandlerContext, params):
    obj = TT.Experimental_TransformGaussianBroadening(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4])
    return _register(obj, 'Experimental_TransformGaussianBroadening', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_TransformDeadtime")
def _ctor_Experimental_TransformDeadtime(ctx: HandlerContext, params):
    obj = TT.Experimental_TransformDeadtime(_lookup(ctx.registry, params[0]), params[1], params[2], params[3])
    return _register(obj, 'Experimental_TransformDeadtime', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_TransformCrosstalk")
def _ctor_Experimental_TransformCrosstalk(ctx: HandlerContext, params):
    obj = TT.Experimental_TransformCrosstalk(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4], params[5])
    return _register(obj, 'Experimental_TransformCrosstalk', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_SimDetector")
def _ctor_Experimental_SimDetector(ctx: HandlerContext, params):
    obj = TT.Experimental_SimDetector(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4], params[5], params[6])
    return _register(obj, 'Experimental_SimDetector', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_SimLifetime")
def _ctor_Experimental_SimLifetime(ctx: HandlerContext, params):
    obj = TT.Experimental_SimLifetime(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4])
    return _register(obj, 'Experimental_SimLifetime', ctx.session_id, ctx.registry, ctx.sessions)

@handler("StartStop")
def _ctor_StartStop(ctx: HandlerContext, params):
    obj = TT.StartStop(*params)
    return _register(obj, 'StartStop', ctx.session_id, ctx.registry, ctx.sessions)

@handler("SynchronizedMeasurements")
def _ctor_SynchronizedMeasurements(ctx: HandlerContext, params):
    obj = TT.SynchronizedMeasurements(_lookup(ctx.registry, params[0]))
    return _register(obj, 'SynchronizedMeasurements', ctx.session_id, ctx.registry, ctx.sessions)

@handler("SyntheticSingleTag")
def _ctor_SyntheticSingleTag(ctx: HandlerContext, params):
    obj = TT.SyntheticSingleTag(*params)
    return _register(obj, 'SyntheticSingleTag', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeDifferences")
def _ctor_TimeDifferences(ctx: HandlerContext, params):
    obj = TT.TimeDifferences(*params)
    return _register(obj, 'TimeDifferences', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Histogram")
def _ctor_Histogram(ctx: HandlerContext, params):
    obj = TT.Histogram(*params)
    return _register(obj, 'Histogram', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeDifferencesND")
def _ctor_TimeDifferencesND(ctx: HandlerContext, params):
    obj = TT.TimeDifferencesND(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4], params[5], params[6], params[7])
    return _register(obj, 'TimeDifferencesND', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeTagStream")
def _ctor_TimeTagStream(ctx: HandlerContext, params):
    obj = TT.TimeTagStream(_lookup(ctx.registry, params[0]), params[1], params[2])
    return _register(obj, 'TimeTagStream', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeTagStreamBuffer")
def _ctor_TimeTagStreamBuffer(ctx: HandlerContext, params):
    obj = TT.TimeTagStreamBuffer(*params)
    return _register(obj, 'TimeTagStreamBuffer', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TriggerOnCountrate")
def _ctor_TriggerOnCountrate(ctx: HandlerContext, params):
    obj = TT.TriggerOnCountrate(_lookup(ctx.registry, params[0]), params[1], params[2], params[3], params[4])
    return _register(obj, 'TriggerOnCountrate', ctx.session_id, ctx.registry, ctx.sessions)

# Instance methods

@handler("SoftwareClockState.clock_period")
def _m_SoftwareClockState_clock_period(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.clock_period()

@handler("SoftwareClockState.input_channel")
def _m_SoftwareClockState_input_channel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.input_channel()

@handler("SoftwareClockState.ideal_clock_channel")
def _m_SoftwareClockState_ideal_clock_channel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.ideal_clock_channel()

@handler("SoftwareClockState.averaging_periods")
def _m_SoftwareClockState_averaging_periods(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.averaging_periods()

@handler("SoftwareClockState.enabled")
def _m_SoftwareClockState_enabled(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.enabled()

@handler("SoftwareClockState.is_locked")
def _m_SoftwareClockState_is_locked(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.is_locked()

@handler("SoftwareClockState.error_counter")
def _m_SoftwareClockState_error_counter(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.error_counter()

@handler("SoftwareClockState.last_ideal_clock_event")
def _m_SoftwareClockState_last_ideal_clock_event(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.last_ideal_clock_event()

@handler("SoftwareClockState.period_error")
def _m_SoftwareClockState_period_error(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.period_error()

@handler("SoftwareClockState.phase_error_estimation")
def _m_SoftwareClockState_phase_error_estimation(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.phase_error_estimation()

@handler("ReferenceClockState.clock_period")
def _m_ReferenceClockState_clock_period(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.clock_period()

@handler("ReferenceClockState.clock_channel")
def _m_ReferenceClockState_clock_channel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.clock_channel()

@handler("ReferenceClockState.synchronization_channel")
def _m_ReferenceClockState_synchronization_channel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.synchronization_channel()

@handler("ReferenceClockState.ideal_clock_channel")
def _m_ReferenceClockState_ideal_clock_channel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.ideal_clock_channel()

@handler("ReferenceClockState.averaging_periods")
def _m_ReferenceClockState_averaging_periods(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.averaging_periods()

@handler("ReferenceClockState.synchronization_offset")
def _m_ReferenceClockState_synchronization_offset(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.synchronization_offset()

@handler("ReferenceClockState.enabled")
def _m_ReferenceClockState_enabled(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.enabled()

@handler("ReferenceClockState.event_divider")
def _m_ReferenceClockState_event_divider(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.event_divider()

@handler("ReferenceClockState.is_locked")
def _m_ReferenceClockState_is_locked(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.is_locked()

@handler("ReferenceClockState.is_synchronized")
def _m_ReferenceClockState_is_synchronized(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.is_synchronized()

@handler("ReferenceClockState.error_counter")
def _m_ReferenceClockState_error_counter(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.error_counter()

@handler("ReferenceClockState.last_ideal_clock_event")
def _m_ReferenceClockState_last_ideal_clock_event(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.last_ideal_clock_event()

@handler("ReferenceClockState.period_error")
def _m_ReferenceClockState_period_error(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.period_error()

@handler("ReferenceClockState.phase_error_estimation")
def _m_ReferenceClockState_phase_error_estimation(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.phase_error_estimation()

@handler("TimeTaggerSource.setInputDelay")
def _m_TimeTaggerSource_setInputDelay(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setInputDelay(params[1], params[2])

@handler("TimeTaggerSource.getInputDelay")
def _m_TimeTaggerSource_getInputDelay(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getInputDelay(params[1])

@handler("TimeTaggerSource.setDelayHardware")
def _m_TimeTaggerSource_setDelayHardware(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setDelayHardware(params[1], params[2])

@handler("TimeTaggerSource.getDelayHardware")
def _m_TimeTaggerSource_getDelayHardware(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getDelayHardware(params[1])

@handler("TimeTaggerSource.getDelayHardwareRange")
def _m_TimeTaggerSource_getDelayHardwareRange(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getDelayHardwareRange(params[1])

@handler("TimeTaggerSource.setDelaySoftware")
def _m_TimeTaggerSource_setDelaySoftware(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setDelaySoftware(params[1], params[2])

@handler("TimeTaggerSource.getDelaySoftware")
def _m_TimeTaggerSource_getDelaySoftware(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getDelaySoftware(params[1])

@handler("TimeTaggerSource.setDeadtime")
def _m_TimeTaggerSource_setDeadtime(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setDeadtime(params[1], params[2])

@handler("TimeTaggerSource.getDeadtime")
def _m_TimeTaggerSource_getDeadtime(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getDeadtime(params[1])

@handler("TimeTaggerSource.getDeadtimeRange")
def _m_TimeTaggerSource_getDeadtimeRange(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getDeadtimeRange(params[1])

@handler("TimeTaggerSource.setConditionalFilter")
def _m_TimeTaggerSource_setConditionalFilter(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setConditionalFilter(params[1], params[2])

@handler("TimeTaggerSource.clearConditionalFilter")
def _m_TimeTaggerSource_clearConditionalFilter(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.clearConditionalFilter()

@handler("TimeTaggerSource.getConditionalFilterTrigger")
def _m_TimeTaggerSource_getConditionalFilterTrigger(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getConditionalFilterTrigger()

@handler("TimeTaggerSource.getConditionalFilterFiltered")
def _m_TimeTaggerSource_getConditionalFilterFiltered(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getConditionalFilterFiltered()

@handler("TimeTaggerSource.setEventDivider")
def _m_TimeTaggerSource_setEventDivider(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setEventDivider(params[1], params[2])

@handler("TimeTaggerSource.getEventDivider")
def _m_TimeTaggerSource_getEventDivider(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getEventDivider(params[1])

@handler("TimeTaggerSource.getOverflows")
def _m_TimeTaggerSource_getOverflows(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getOverflows()

@handler("TimeTaggerSource.getOverflowsAndClear")
def _m_TimeTaggerSource_getOverflowsAndClear(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getOverflowsAndClear()

@handler("TimeTaggerSource.clearOverflows")
def _m_TimeTaggerSource_clearOverflows(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.clearOverflows()

@handler("TimeTaggerSource.setReferenceClock")
def _m_TimeTaggerSource_setReferenceClock(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setReferenceClock(*params[1:])

@handler("TimeTaggerSource.disableReferenceClock")
def _m_TimeTaggerSource_disableReferenceClock(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.disableReferenceClock()

@handler("TimeTaggerSource.getReferenceClockState")
def _m_TimeTaggerSource_getReferenceClockState(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getReferenceClockState()
    return _register(result, 'ReferenceClockState', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeTaggerBase.setSoftwareClock")
def _m_TimeTaggerBase_setSoftwareClock(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setSoftwareClock(params[1], params[2], params[3], params[4])

@handler("TimeTaggerBase.disableSoftwareClock")
def _m_TimeTaggerBase_disableSoftwareClock(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.disableSoftwareClock()

@handler("TimeTaggerBase.getSoftwareClockState")
def _m_TimeTaggerBase_getSoftwareClockState(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getSoftwareClockState()
    return _register(result, 'SoftwareClockState', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeTaggerBase.getFence")
def _m_TimeTaggerBase_getFence(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getFence(params[1])

@handler("TimeTaggerBase.getInvertedChannel")
def _m_TimeTaggerBase_getInvertedChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getInvertedChannel(params[1])

@handler("TimeTaggerBase.isUnusedChannel")
def _m_TimeTaggerBase_isUnusedChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.isUnusedChannel(params[1])

@handler("TimeTaggerBase.getConfiguration")
def _m_TimeTaggerBase_getConfiguration(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getConfiguration()

@handler("TimeTaggerBase.getRegistrations")
def _m_TimeTaggerBase_getRegistrations(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getRegistrations(params[1])

@handler("TimeTaggerBase.isChannelRegistered")
def _m_TimeTaggerBase_isChannelRegistered(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.isChannelRegistered(params[1])

@handler("TimeTaggerBase.xtra_setAutoStart")
def _m_TimeTaggerBase_xtra_setAutoStart(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_setAutoStart(params[1])

@handler("TimeTaggerBase.xtra_getAutoStart")
def _m_TimeTaggerBase_xtra_getAutoStart(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_getAutoStart()

@handler("TimeTaggerBase.sync")
def _m_TimeTaggerBase_sync(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.sync(params[1])

@handler("TimeTaggerBase.waitForFence")
def _m_TimeTaggerBase_waitForFence(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.waitForFence(params[1], params[2])

@handler("TimeTaggerHardware.setTriggerLevel")
def _m_TimeTaggerHardware_setTriggerLevel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setTriggerLevel(params[1], params[2])

@handler("TimeTaggerHardware.getTriggerLevel")
def _m_TimeTaggerHardware_getTriggerLevel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getTriggerLevel(params[1])

@handler("TimeTaggerHardware.getHardwareDelayCompensation")
def _m_TimeTaggerHardware_getHardwareDelayCompensation(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getHardwareDelayCompensation(params[1])

@handler("TimeTaggerHardware.setHardwareDelayCompensationActive")
def _m_TimeTaggerHardware_setHardwareDelayCompensationActive(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setHardwareDelayCompensationActive(params[1])

@handler("TimeTaggerHardware.setInputImpedanceHigh")
def _m_TimeTaggerHardware_setInputImpedanceHigh(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setInputImpedanceHigh(params[1], params[2])

@handler("TimeTaggerHardware.getInputImpedanceHigh")
def _m_TimeTaggerHardware_getInputImpedanceHigh(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getInputImpedanceHigh(params[1])

@handler("TimeTaggerHardware.setInputHysteresis")
def _m_TimeTaggerHardware_setInputHysteresis(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setInputHysteresis(params[1], params[2])

@handler("TimeTaggerHardware.getInputHysteresis")
def _m_TimeTaggerHardware_getInputHysteresis(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getInputHysteresis(params[1])

@handler("TimeTaggerHardware.setNormalization")
def _m_TimeTaggerHardware_setNormalization(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setNormalization(params[1], params[2])

@handler("TimeTaggerHardware.getNormalization")
def _m_TimeTaggerHardware_getNormalization(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getNormalization(params[1])

@handler("TimeTaggerHardware.getSerial")
def _m_TimeTaggerHardware_getSerial(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getSerial()

@handler("TimeTaggerHardware.getModel")
def _m_TimeTaggerHardware_getModel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getModel()

@handler("TimeTaggerHardware.getPcbVersion")
def _m_TimeTaggerHardware_getPcbVersion(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getPcbVersion()

@handler("TimeTaggerHardware.getFirmwareVersion")
def _m_TimeTaggerHardware_getFirmwareVersion(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getFirmwareVersion()

@handler("TimeTaggerHardware.getDACRange")
def _m_TimeTaggerHardware_getDACRange(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getDACRange()

@handler("TimeTaggerHardware.getTriggerLevelRange")
def _m_TimeTaggerHardware_getTriggerLevelRange(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getTriggerLevelRange(params[1])

@handler("TimeTaggerHardware.getChannelList")
def _m_TimeTaggerHardware_getChannelList(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannelList(*params[1:])

@handler("TimeTaggerHardware.setHardwareBufferSize")
def _m_TimeTaggerHardware_setHardwareBufferSize(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setHardwareBufferSize(params[1])

@handler("TimeTaggerHardware.getHardwareBufferSize")
def _m_TimeTaggerHardware_getHardwareBufferSize(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getHardwareBufferSize()

@handler("TimeTaggerHardware.getPsPerClock")
def _m_TimeTaggerHardware_getPsPerClock(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getPsPerClock()

@handler("TimeTaggerHardware.setStreamBlockSize")
def _m_TimeTaggerHardware_setStreamBlockSize(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setStreamBlockSize(params[1], params[2])

@handler("TimeTaggerHardware.getStreamBlockSizeEvents")
def _m_TimeTaggerHardware_getStreamBlockSizeEvents(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getStreamBlockSizeEvents()

@handler("TimeTaggerHardware.getStreamBlockSizeLatency")
def _m_TimeTaggerHardware_getStreamBlockSizeLatency(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getStreamBlockSizeLatency()

@handler("TimeTaggerHardware.setTestSignal")
def _m_TimeTaggerHardware_setTestSignal(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setTestSignal(*params[1:])

@handler("TimeTaggerHardware.getTestSignal")
def _m_TimeTaggerHardware_getTestSignal(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getTestSignal(params[1])

@handler("TimeTaggerHardware.setTestSignalDivider")
def _m_TimeTaggerHardware_setTestSignalDivider(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setTestSignalDivider(params[1])

@handler("TimeTaggerHardware.getTestSignalDivider")
def _m_TimeTaggerHardware_getTestSignalDivider(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getTestSignalDivider()

@handler("TimeTaggerHardware.getDeviceLicense")
def _m_TimeTaggerHardware_getDeviceLicense(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getDeviceLicense()

@handler("TimeTaggerHardware.getSensorData")
def _m_TimeTaggerHardware_getSensorData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getSensorData()

@handler("TimeTaggerHardware.disableLEDs")
def _m_TimeTaggerHardware_disableLEDs(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.disableLEDs(params[1])

@handler("TimeTaggerHardware.setLED")
def _m_TimeTaggerHardware_setLED(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setLED(params[1])

@handler("TimeTaggerHardware.setSoundFrequency")
def _m_TimeTaggerHardware_setSoundFrequency(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setSoundFrequency(params[1])

@handler("TimeTaggerHardware.setTimeTaggerNetworkStreamCompression")
def _m_TimeTaggerHardware_setTimeTaggerNetworkStreamCompression(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setTimeTaggerNetworkStreamCompression(params[1])

@handler("TimeTaggerHardware.getChannelNumberScheme")
def _m_TimeTaggerHardware_getChannelNumberScheme(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannelNumberScheme()

@handler("TimeTaggerVirtual.run")
def _m_TimeTaggerVirtual_run(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.run(params[1])

@handler("TimeTaggerVirtual.replay")
def _m_TimeTaggerVirtual_replay(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.replay(params[1], params[2], params[3], params[4])

@handler("TimeTaggerVirtual.stop")
def _m_TimeTaggerVirtual_stop(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.stop()

@handler("TimeTaggerVirtual.appendFile")
def _m_TimeTaggerVirtual_appendFile(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.appendFile(params[1], params[2], params[3], params[4])

@handler("TimeTaggerVirtual.setReplaySpeed")
def _m_TimeTaggerVirtual_setReplaySpeed(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setReplaySpeed(params[1])

@handler("TimeTaggerVirtual.getReplaySpeed")
def _m_TimeTaggerVirtual_getReplaySpeed(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getReplaySpeed()

@handler("TimeTaggerVirtual.reset")
def _m_TimeTaggerVirtual_reset(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.reset()

@handler("TimeTaggerVirtual.getChannelList")
def _m_TimeTaggerVirtual_getChannelList(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannelList()

@handler("TimeTaggerVirtual.setTestSignal")
def _m_TimeTaggerVirtual_setTestSignal(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setTestSignal(*params[1:])

@handler("TimeTaggerVirtual.getTestSignal")
def _m_TimeTaggerVirtual_getTestSignal(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getTestSignal(params[1])

@handler("TimeTaggerVirtual.waitForCompletion")
def _m_TimeTaggerVirtual_waitForCompletion(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.waitForCompletion(params[1], params[2])

@handler("TimeTaggerVirtual.waitUntilFinished")
def _m_TimeTaggerVirtual_waitUntilFinished(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.waitUntilFinished(params[1], params[2])

@handler("TimeTaggerServer.getAddress")
def _m_TimeTaggerServer_getAddress(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getAddress()

@handler("TimeTaggerServer.getAccessMode")
def _m_TimeTaggerServer_getAccessMode(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getAccessMode()
    return _register(result, 'AccessMode', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeTaggerServer.getClientChannel")
def _m_TimeTaggerServer_getClientChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getClientChannel(params[1])

@handler("TimeTaggerNetwork.isConnected")
def _m_TimeTaggerNetwork_isConnected(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.isConnected()

@handler("TimeTaggerNetwork.setDelayClient")
def _m_TimeTaggerNetwork_setDelayClient(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setDelayClient(params[1], params[2])

@handler("TimeTaggerNetwork.getDelayClient")
def _m_TimeTaggerNetwork_getDelayClient(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getDelayClient(params[1])

@handler("TimeTaggerNetwork.getOverflowsClient")
def _m_TimeTaggerNetwork_getOverflowsClient(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getOverflowsClient()

@handler("TimeTaggerNetwork.getOverflowsAndClearClient")
def _m_TimeTaggerNetwork_getOverflowsAndClearClient(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getOverflowsAndClearClient()

@handler("TimeTaggerNetwork.clearOverflowsClient")
def _m_TimeTaggerNetwork_clearOverflowsClient(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.clearOverflowsClient()

@handler("TimeTaggerNetwork.getServer")
def _m_TimeTaggerNetwork_getServer(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getServer(params[1])
    return _register(result, 'TimeTaggerServer', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeTaggerNetwork.getServers")
def _m_TimeTaggerNetwork_getServers(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getServers()

@handler("TimeTagger.reset")
def _m_TimeTagger_reset(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.reset()

@handler("TimeTagger.autoCalibration")
def _m_TimeTagger_autoCalibration(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.autoCalibration()

@handler("TimeTagger.getDistributionCount")
def _m_TimeTagger_getDistributionCount(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getDistributionCount())

@handler("TimeTagger.getDistributionPSecs")
def _m_TimeTagger_getDistributionPSecs(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getDistributionPSecs())

@handler("TimeTagger.enableFpgaLink")
def _m_TimeTagger_enableFpgaLink(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.enableFpgaLink(*params[1:])

@handler("TimeTagger.disableFpgaLink")
def _m_TimeTagger_disableFpgaLink(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.disableFpgaLink()

@handler("TimeTagger.startServer")
def _m_TimeTagger_startServer(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.startServer(*params[1:])

@handler("TimeTagger.stopServer")
def _m_TimeTagger_stopServer(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.stopServer()

@handler("TimeTagger.isServerRunning")
def _m_TimeTagger_isServerRunning(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.isServerRunning()

@handler("TimeTagger.setServerAddress")
def _m_TimeTagger_setServerAddress(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setServerAddress(params[1])

@handler("TimeTagger.getServerAddress")
def _m_TimeTagger_getServerAddress(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getServerAddress()

@handler("TimeTagger.getConnectedClients")
def _m_TimeTagger_getConnectedClients(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getConnectedClients()

@handler("TimeTagger.xtra_setAvgRisingFalling")
def _m_TimeTagger_xtra_setAvgRisingFalling(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_setAvgRisingFalling(params[1], params[2])

@handler("TimeTagger.xtra_getAvgRisingFalling")
def _m_TimeTagger_xtra_getAvgRisingFalling(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_getAvgRisingFalling(params[1])

@handler("TimeTagger.xtra_setHighPrioChannel")
def _m_TimeTagger_xtra_setHighPrioChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_setHighPrioChannel(params[1], params[2])

@handler("TimeTagger.xtra_getHighPrioChannel")
def _m_TimeTagger_xtra_getHighPrioChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_getHighPrioChannel(params[1])

@handler("TimeTagger.xtra_setAuxOut")
def _m_TimeTagger_xtra_setAuxOut(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_setAuxOut(params[1], params[2])

@handler("TimeTagger.xtra_getAuxOut")
def _m_TimeTagger_xtra_getAuxOut(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_getAuxOut(params[1])

@handler("TimeTagger.xtra_setAuxOutSignal")
def _m_TimeTagger_xtra_setAuxOutSignal(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_setAuxOutSignal(params[1], params[2], params[3])

@handler("TimeTagger.xtra_getAuxOutSignalDivider")
def _m_TimeTagger_xtra_getAuxOutSignalDivider(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_getAuxOutSignalDivider(params[1])

@handler("TimeTagger.xtra_getAuxOutSignalDutyCycle")
def _m_TimeTagger_xtra_getAuxOutSignalDutyCycle(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_getAuxOutSignalDutyCycle(params[1])

@handler("TimeTagger.xtra_measureTriggerLevel")
def _m_TimeTagger_xtra_measureTriggerLevel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_measureTriggerLevel(params[1])

@handler("TimeTagger.xtra_setClockSource")
def _m_TimeTagger_xtra_setClockSource(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_setClockSource(params[1])

@handler("TimeTagger.xtra_getClockSource")
def _m_TimeTagger_xtra_getClockSource(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_getClockSource()

@handler("TimeTagger.xtra_setClockAutoSelect")
def _m_TimeTagger_xtra_setClockAutoSelect(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_setClockAutoSelect(params[1])

@handler("TimeTagger.xtra_getClockAutoSelect")
def _m_TimeTagger_xtra_getClockAutoSelect(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_getClockAutoSelect()

@handler("TimeTagger.xtra_setClockOut")
def _m_TimeTagger_xtra_setClockOut(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_setClockOut(params[1])

@handler("TimeTagger.xtra_setFanSpeed")
def _m_TimeTagger_xtra_setFanSpeed(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.xtra_setFanSpeed(params[1])

@handler("TimeTagger.setInputMux")
def _m_TimeTagger_setInputMux(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setInputMux(params[1], params[2])

@handler("TimeTagger.getInputMux")
def _m_TimeTagger_getInputMux(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getInputMux(params[1])

@handler("TimeTagger.updateBMCFirmware")
def _m_TimeTagger_updateBMCFirmware(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.updateBMCFirmware(params[1])

@handler("ChannelGate.gate_open_channel")
def _m_ChannelGate_gate_open_channel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.gate_open_channel()

@handler("ChannelGate.gate_close_channel")
def _m_ChannelGate_gate_close_channel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.gate_close_channel()

@handler("ChannelGate.initial")
def _m_ChannelGate_initial(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.initial()

@handler("Coincidences.getChannels")
def _m_Coincidences_getChannels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannels()

@handler("Coincidences.setCoincidenceWindow")
def _m_Coincidences_setCoincidenceWindow(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setCoincidenceWindow(params[1])

@handler("Coincidence.getChannel")
def _m_Coincidence_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("Combinations.getChannel")
def _m_Combinations_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel(params[1])

@handler("Combinations.getChannels")
def _m_Combinations_getChannels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannels(params[1])

@handler("Combinations.getChannelByMask")
def _m_Combinations_getChannelByMask(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannelByMask(params[1])

@handler("Combinations.getCombination")
def _m_Combinations_getCombination(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getCombination(params[1])

@handler("Combinations.getSumChannel")
def _m_Combinations_getSumChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getSumChannel(params[1])

@handler("Combiner.getChannelCounts")
def _m_Combiner_getChannelCounts(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getChannelCounts())

@handler("Combiner.getData")
def _m_Combiner_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("Combiner.getChannel")
def _m_Combiner_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("ConditionalFilterChannel.getChannel")
def _m_ConditionalFilterChannel_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("ConditionalFilterChannel.getChannels")
def _m_ConditionalFilterChannel_getChannels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannels()

@handler("ConstantFractionDiscriminator.getChannels")
def _m_ConstantFractionDiscriminator_getChannels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannels()

@handler("Correlation.getData")
def _m_Correlation_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("Correlation.getDataNormalized")
def _m_Correlation_getDataNormalized(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getDataNormalized())

@handler("Correlation.getIndex")
def _m_Correlation_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("CorrelationPairsData.getCounts")
def _m_CorrelationPairsData_getCounts(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getCounts(params[1]))

@handler("CorrelationPairsData.getG2")
def _m_CorrelationPairsData_getG2(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getG2(params[1]))

@handler("CorrelationPairsData.getIndex")
def _m_CorrelationPairsData_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("CorrelationPairsData.discard")
def _m_CorrelationPairsData_discard(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.discard()

@handler("CorrelationPairs.getDataObject")
def _m_CorrelationPairs_getDataObject(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getDataObject()
    return _register(result, 'CorrelationPairsData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("CorrelationPairs.getIndex")
def _m_CorrelationPairs_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("CountBetweenMarkers.getData")
def _m_CountBetweenMarkers_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("CountBetweenMarkers.getIndex")
def _m_CountBetweenMarkers_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("CountBetweenMarkers.getBinWidths")
def _m_CountBetweenMarkers_getBinWidths(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getBinWidths())

@handler("CountBetweenMarkers.ready")
def _m_CountBetweenMarkers_ready(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.ready()

@handler("CounterData.getIndex")
def _m_CounterData_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("CounterData.getData")
def _m_CounterData_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("CounterData.getDataNormalized")
def _m_CounterData_getDataNormalized(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getDataNormalized())

@handler("CounterData.getFrequency")
def _m_CounterData_getFrequency(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getFrequency(*params[1:]))

@handler("CounterData.getDataTotalCounts")
def _m_CounterData_getDataTotalCounts(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getDataTotalCounts())

@handler("CounterData.getTime")
def _m_CounterData_getTime(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getTime())

@handler("CounterData.getOverflowMask")
def _m_CounterData_getOverflowMask(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getOverflowMask())

@handler("CounterData.getChannels")
def _m_CounterData_getChannels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getChannels())

@handler("CounterData.size")
def _m_CounterData_size(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.size()

@handler("CounterData.dropped_bins")
def _m_CounterData_dropped_bins(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.dropped_bins()

@handler("CounterData.overflow")
def _m_CounterData_overflow(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.overflow()

@handler("CounterData.discard")
def _m_CounterData_discard(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.discard()

@handler("Counter.getData")
def _m_Counter_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData(params[1]))

@handler("Counter.getIndex")
def _m_Counter_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("Counter.getDataNormalized")
def _m_Counter_getDataNormalized(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getDataNormalized(params[1]))

@handler("Counter.getDataTotalCounts")
def _m_Counter_getDataTotalCounts(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getDataTotalCounts())

@handler("Counter.getDataObject")
def _m_Counter_getDataObject(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getDataObject(params[1])
    return _register(result, 'CounterData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Countrate.getData")
def _m_Countrate_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("Countrate.getCountsTotal")
def _m_Countrate_getCountsTotal(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getCountsTotal())

@handler("DelayedChannels.getChannels")
def _m_DelayedChannels_getChannels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannels()

@handler("DelayedChannels.setDelay")
def _m_DelayedChannels_setDelay(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setDelay(params[1])

@handler("DelayedChannel.getChannel")
def _m_DelayedChannel_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("EventGenerator.getChannel")
def _m_EventGenerator_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("FileReader.getData")
def _m_FileReader_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getData(params[1])
    return _register(result, 'TimeTagStreamBuffer', ctx.session_id, ctx.registry, ctx.sessions)

@handler("FileReader.hasData")
def _m_FileReader_hasData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.hasData()

@handler("FileReader.getConfiguration")
def _m_FileReader_getConfiguration(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getConfiguration()

@handler("FileReader.getChannelList")
def _m_FileReader_getChannelList(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannelList()

@handler("FileReader.getLastMarker")
def _m_FileReader_getLastMarker(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getLastMarker()

@handler("FileWriter.split")
def _m_FileWriter_split(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.split(*params[1:])

@handler("FileWriter.setMaxFileSize")
def _m_FileWriter_setMaxFileSize(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setMaxFileSize(params[1])

@handler("FileWriter.getMaxFileSize")
def _m_FileWriter_getMaxFileSize(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getMaxFileSize()

@handler("FileWriter.getTotalEvents")
def _m_FileWriter_getTotalEvents(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getTotalEvents()

@handler("FileWriter.getTotalSize")
def _m_FileWriter_getTotalSize(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getTotalSize()

@handler("FileWriter.setMarker")
def _m_FileWriter_setMarker(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setMarker(params[1])

@handler("FlimFrameInfo.getFrameNumber")
def _m_FlimFrameInfo_getFrameNumber(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getFrameNumber()

@handler("FlimFrameInfo.isValid")
def _m_FlimFrameInfo_isValid(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.isValid()

@handler("FlimFrameInfo.getPixelPosition")
def _m_FlimFrameInfo_getPixelPosition(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getPixelPosition()

@handler("FlimFrameInfo.getHistograms")
def _m_FlimFrameInfo_getHistograms(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getHistograms())

@handler("FlimFrameInfo.getIntensities")
def _m_FlimFrameInfo_getIntensities(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIntensities())

@handler("FlimFrameInfo.getSummedCounts")
def _m_FlimFrameInfo_getSummedCounts(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getSummedCounts())

@handler("FlimFrameInfo.getPixelBegins")
def _m_FlimFrameInfo_getPixelBegins(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getPixelBegins())

@handler("FlimFrameInfo.getPixelEnds")
def _m_FlimFrameInfo_getPixelEnds(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getPixelEnds())

@handler("FlimFrameInfo.pixels")
def _m_FlimFrameInfo_pixels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.pixels()

@handler("FlimFrameInfo.bins")
def _m_FlimFrameInfo_bins(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.bins()

@handler("FlimFrameInfo.frame_number")
def _m_FlimFrameInfo_frame_number(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.frame_number()

@handler("FlimFrameInfo.pixel_position")
def _m_FlimFrameInfo_pixel_position(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.pixel_position()

@handler("FlimFrameInfo.valid")
def _m_FlimFrameInfo_valid(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.valid()

@handler("FlimFrameInfo.discard")
def _m_FlimFrameInfo_discard(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.discard()

@handler("Flim.getCurrentFrame")
def _m_Flim_getCurrentFrame(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getCurrentFrame())

@handler("Flim.getCurrentFrameEx")
def _m_Flim_getCurrentFrameEx(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getCurrentFrameEx()
    return _register(result, 'FlimFrameInfo', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Flim.getCurrentFrameIntensity")
def _m_Flim_getCurrentFrameIntensity(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getCurrentFrameIntensity())

@handler("Flim.getFramesAcquired")
def _m_Flim_getFramesAcquired(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getFramesAcquired()

@handler("Flim.getIndex")
def _m_Flim_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("Flim.getReadyFrame")
def _m_Flim_getReadyFrame(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getReadyFrame(params[1]))

@handler("Flim.getReadyFrameEx")
def _m_Flim_getReadyFrameEx(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getReadyFrameEx(params[1])
    return _register(result, 'FlimFrameInfo', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Flim.getReadyFrameIntensity")
def _m_Flim_getReadyFrameIntensity(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getReadyFrameIntensity(params[1]))

@handler("Flim.getSummedFrames")
def _m_Flim_getSummedFrames(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getSummedFrames(params[1], params[2]))

@handler("Flim.getSummedFramesEx")
def _m_Flim_getSummedFramesEx(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getSummedFramesEx(params[1], params[2])
    return _register(result, 'FlimFrameInfo', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Flim.getSummedFramesIntensity")
def _m_Flim_getSummedFramesIntensity(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getSummedFramesIntensity(params[1], params[2]))

@handler("Flim.initialize")
def _m_Flim_initialize(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.initialize()

@handler("Flim.frameReady")
def _m_Flim_frameReady(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.frameReady(params[1], params[2], params[3], params[4], params[5], params[6])

@handler("FrequencyCounterData.getIndex")
def _m_FrequencyCounterData_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("FrequencyCounterData.getTime")
def _m_FrequencyCounterData_getTime(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getTime())

@handler("FrequencyCounterData.getPeriodsCount")
def _m_FrequencyCounterData_getPeriodsCount(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getPeriodsCount())

@handler("FrequencyCounterData.getPeriodsFraction")
def _m_FrequencyCounterData_getPeriodsFraction(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getPeriodsFraction())

@handler("FrequencyCounterData.getPhase")
def _m_FrequencyCounterData_getPhase(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getPhase(params[1]))

@handler("FrequencyCounterData.getFrequency")
def _m_FrequencyCounterData_getFrequency(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getFrequency(*params[1:]))

@handler("FrequencyCounterData.getFrequencyInstantaneous")
def _m_FrequencyCounterData_getFrequencyInstantaneous(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getFrequencyInstantaneous())

@handler("FrequencyCounterData.getOverflowMask")
def _m_FrequencyCounterData_getOverflowMask(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getOverflowMask())

@handler("FrequencyCounterData.size")
def _m_FrequencyCounterData_size(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.size()

@handler("FrequencyCounterData.overflow_samples")
def _m_FrequencyCounterData_overflow_samples(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.overflow_samples()

@handler("FrequencyCounterData.align_to_reference")
def _m_FrequencyCounterData_align_to_reference(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.align_to_reference()

@handler("FrequencyCounterData.sampling_interval")
def _m_FrequencyCounterData_sampling_interval(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.sampling_interval()

@handler("FrequencyCounterData.sample_offset")
def _m_FrequencyCounterData_sample_offset(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.sample_offset()

@handler("FrequencyCounterData.channels_last_dim")
def _m_FrequencyCounterData_channels_last_dim(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.channels_last_dim()

@handler("FrequencyCounterData.discard")
def _m_FrequencyCounterData_discard(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.discard()

@handler("FrequencyCounter.getDataObject")
def _m_FrequencyCounter_getDataObject(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getDataObject(params[1], params[2], params[3])
    return _register(result, 'FrequencyCounterData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("FrequencyMultiplier.getChannel")
def _m_FrequencyMultiplier_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("FrequencyMultiplier.getMultiplier")
def _m_FrequencyMultiplier_getMultiplier(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getMultiplier()

@handler("FrequencyStabilityData.getTau")
def _m_FrequencyStabilityData_getTau(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getTau())

@handler("FrequencyStabilityData.getADEV")
def _m_FrequencyStabilityData_getADEV(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getADEV())

@handler("FrequencyStabilityData.getMDEV")
def _m_FrequencyStabilityData_getMDEV(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getMDEV())

@handler("FrequencyStabilityData.getHDEV")
def _m_FrequencyStabilityData_getHDEV(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getHDEV())

@handler("FrequencyStabilityData.getSTDD")
def _m_FrequencyStabilityData_getSTDD(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getSTDD())

@handler("FrequencyStabilityData.getADEVScaled")
def _m_FrequencyStabilityData_getADEVScaled(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getADEVScaled())

@handler("FrequencyStabilityData.getTDEV")
def _m_FrequencyStabilityData_getTDEV(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getTDEV())

@handler("FrequencyStabilityData.getHDEVScaled")
def _m_FrequencyStabilityData_getHDEVScaled(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getHDEVScaled())

@handler("FrequencyStabilityData.getTraceIndex")
def _m_FrequencyStabilityData_getTraceIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getTraceIndex())

@handler("FrequencyStabilityData.getTracePhase")
def _m_FrequencyStabilityData_getTracePhase(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getTracePhase())

@handler("FrequencyStabilityData.getTraceFrequency")
def _m_FrequencyStabilityData_getTraceFrequency(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getTraceFrequency())

@handler("FrequencyStabilityData.getTraceFrequencyAbsolute")
def _m_FrequencyStabilityData_getTraceFrequencyAbsolute(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getTraceFrequencyAbsolute(params[1]))

@handler("FrequencyStabilityData.discard")
def _m_FrequencyStabilityData_discard(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.discard()

@handler("FrequencyStability.getDataObject")
def _m_FrequencyStability_getDataObject(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getDataObject()
    return _register(result, 'FrequencyStabilityData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("GatedChannel.getChannel")
def _m_GatedChannel_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("HistogramLogBinsData.getG2")
def _m_HistogramLogBinsData_getG2(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getG2())

@handler("HistogramLogBinsData.getCounts")
def _m_HistogramLogBinsData_getCounts(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getCounts())

@handler("HistogramLogBinsData.getG2Normalization")
def _m_HistogramLogBinsData_getG2Normalization(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getG2Normalization())

@handler("HistogramLogBinsData.accumulation_time_start")
def _m_HistogramLogBinsData_accumulation_time_start(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.accumulation_time_start()

@handler("HistogramLogBinsData.accumulation_time_click")
def _m_HistogramLogBinsData_accumulation_time_click(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.accumulation_time_click()

@handler("HistogramLogBinsData.discard")
def _m_HistogramLogBinsData_discard(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.discard()

@handler("HistogramLogBins.getDataObject")
def _m_HistogramLogBins_getDataObject(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getDataObject()
    return _register(result, 'HistogramLogBinsData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("HistogramLogBins.getBinEdges")
def _m_HistogramLogBins_getBinEdges(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getBinEdges())

@handler("HistogramLogBins.getData")
def _m_HistogramLogBins_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("HistogramLogBins.getDataNormalizedCountsPerPs")
def _m_HistogramLogBins_getDataNormalizedCountsPerPs(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getDataNormalizedCountsPerPs())

@handler("HistogramLogBins.getDataNormalizedG2")
def _m_HistogramLogBins_getDataNormalizedG2(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getDataNormalizedG2())

@handler("Histogram2D.getData")
def _m_Histogram2D_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("Histogram2D.getIndex")
def _m_Histogram2D_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("Histogram2D.getIndex_1")
def _m_Histogram2D_getIndex_1(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex_1())

@handler("Histogram2D.getIndex_2")
def _m_Histogram2D_getIndex_2(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex_2())

@handler("HistogramND.getData")
def _m_HistogramND_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("HistogramND.getIndex")
def _m_HistogramND_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex(params[1]))

@handler("Experimental_MarkovProcessGenerator.getChannel")
def _m_Experimental_MarkovProcessGenerator_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("Experimental_MarkovProcessGenerator.getChannels")
def _m_Experimental_MarkovProcessGenerator_getChannels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannels()

@handler("PhaseNoiseData.getPhaseNoise")
def _m_PhaseNoiseData_getPhaseNoise(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getPhaseNoise())

@handler("PhaseNoiseData.getIntegratedJitter")
def _m_PhaseNoiseData_getIntegratedJitter(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getIntegratedJitter(params[1], params[2])

@handler("PhaseNoiseData.getOffset")
def _m_PhaseNoiseData_getOffset(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getOffset())

@handler("PhaseNoiseData.getAveragedSequences")
def _m_PhaseNoiseData_getAveragedSequences(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getAveragedSequences())

@handler("PhaseNoiseData.getFrequency")
def _m_PhaseNoiseData_getFrequency(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getFrequency()

@handler("PhaseNoiseData.discard")
def _m_PhaseNoiseData_discard(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.discard()

@handler("PhaseNoise.getDataObject")
def _m_PhaseNoise_getDataObject(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getDataObject()
    return _register(result, 'PhaseNoiseData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Experimental_PhotonNumber.getChannels")
def _m_Experimental_PhotonNumber_getChannels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannels()

@handler("Experimental_PulsePerSecondData.getIndices")
def _m_Experimental_PulsePerSecondData_getIndices(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndices())

@handler("Experimental_PulsePerSecondData.getReferenceOffsets")
def _m_Experimental_PulsePerSecondData_getReferenceOffsets(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getReferenceOffsets())

@handler("Experimental_PulsePerSecondData.getSignalOffsets")
def _m_Experimental_PulsePerSecondData_getSignalOffsets(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getSignalOffsets())

@handler("Experimental_PulsePerSecondData.getUtcSeconds")
def _m_Experimental_PulsePerSecondData_getUtcSeconds(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getUtcSeconds())

@handler("Experimental_PulsePerSecondData.getUtcDates")
def _m_Experimental_PulsePerSecondData_getUtcDates(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getUtcDates()

@handler("Experimental_PulsePerSecondData.getStatus")
def _m_Experimental_PulsePerSecondData_getStatus(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getStatus())

@handler("Experimental_PulsePerSecondData.size")
def _m_Experimental_PulsePerSecondData_size(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.size()

@handler("Experimental_PulsePerSecondData.discard")
def _m_Experimental_PulsePerSecondData_discard(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.discard()

@handler("Experimental_PulsePerSecondMonitor.getDataObject")
def _m_Experimental_PulsePerSecondMonitor_getDataObject(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getDataObject(params[1])
    return _register(result, 'Experimental_PulsePerSecondData', ctx.session_id, ctx.registry, ctx.sessions)

@handler("Sampler.getData")
def _m_Sampler_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("Sampler.getDataAsMask")
def _m_Sampler_getDataAsMask(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getDataAsMask())

@handler("Scope.getData")
def _m_Scope_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getData()

@handler("Scope.ready")
def _m_Scope_ready(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.ready()

@handler("Scope.triggered")
def _m_Scope_triggered(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.triggered()

@handler("Scope.getWindowSize")
def _m_Scope_getWindowSize(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getWindowSize()

@handler("Experimental_SimSignalSplitter.getChannels")
def _m_Experimental_SimSignalSplitter_getChannels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannels()

@handler("Experimental_SimSignalSplitter.getLeftChannel")
def _m_Experimental_SimSignalSplitter_getLeftChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getLeftChannel()

@handler("Experimental_SimSignalSplitter.getRightChannel")
def _m_Experimental_SimSignalSplitter_getRightChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getRightChannel()

@handler("Experimental_TransformEfficiency.getChannel")
def _m_Experimental_TransformEfficiency_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("Experimental_TransformGaussianBroadening.getChannel")
def _m_Experimental_TransformGaussianBroadening_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("Experimental_TransformDeadtime.getChannel")
def _m_Experimental_TransformDeadtime_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("Experimental_TransformCrosstalk.getChannel")
def _m_Experimental_TransformCrosstalk_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("Experimental_SimDetector.getChannel")
def _m_Experimental_SimDetector_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("Experimental_SimLifetime.getChannel")
def _m_Experimental_SimLifetime_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("Experimental_SimLifetime.registerLifetimeReactor")
def _m_Experimental_SimLifetime_registerLifetimeReactor(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.registerLifetimeReactor(params[1], params[2], params[3])

@handler("Experimental_SimLifetime.registerEmissionReactor")
def _m_Experimental_SimLifetime_registerEmissionReactor(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.registerEmissionReactor(params[1], params[2], params[3])

@handler("StartStop.getData")
def _m_StartStop_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("SynchronizedMeasurements.getTagger")
def _m_SynchronizedMeasurements_getTagger(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getTagger()
    return _register(result, 'TimeTaggerBase', ctx.session_id, ctx.registry, ctx.sessions)

@handler("SynchronizedMeasurements.start")
def _m_SynchronizedMeasurements_start(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.start()

@handler("SynchronizedMeasurements.startFor")
def _m_SynchronizedMeasurements_startFor(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.startFor(params[1], params[2])

@handler("SynchronizedMeasurements.stop")
def _m_SynchronizedMeasurements_stop(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.stop()

@handler("SynchronizedMeasurements.clear")
def _m_SynchronizedMeasurements_clear(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.clear()

@handler("SynchronizedMeasurements.isRunning")
def _m_SynchronizedMeasurements_isRunning(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.isRunning()

@handler("SynchronizedMeasurements.registerMeasurement")
def _m_SynchronizedMeasurements_registerMeasurement(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.registerMeasurement(params[1])

@handler("SynchronizedMeasurements.unregisterMeasurement")
def _m_SynchronizedMeasurements_unregisterMeasurement(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.unregisterMeasurement(params[1])

@handler("SynchronizedMeasurements.waitUntilFinished")
def _m_SynchronizedMeasurements_waitUntilFinished(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.waitUntilFinished(params[1])

@handler("SyntheticSingleTag.trigger")
def _m_SyntheticSingleTag_trigger(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.trigger()

@handler("SyntheticSingleTag.getChannel")
def _m_SyntheticSingleTag_getChannel(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannel()

@handler("TimeDifferences.getData")
def _m_TimeDifferences_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("TimeDifferences.getIndex")
def _m_TimeDifferences_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("TimeDifferences.setMaxCounts")
def _m_TimeDifferences_setMaxCounts(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setMaxCounts(params[1])

@handler("TimeDifferences.setMaxRollovers")
def _m_TimeDifferences_setMaxRollovers(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setMaxRollovers(params[1])

@handler("TimeDifferences.getHistogramIndex")
def _m_TimeDifferences_getHistogramIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getHistogramIndex()

@handler("TimeDifferences.getCounts")
def _m_TimeDifferences_getCounts(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getCounts()

@handler("TimeDifferences.ready")
def _m_TimeDifferences_ready(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.ready()

@handler("Histogram.getData")
def _m_Histogram_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("Histogram.getIndex")
def _m_Histogram_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("TimeDifferencesND.getData")
def _m_TimeDifferencesND_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getData())

@handler("TimeDifferencesND.getIndex")
def _m_TimeDifferencesND_getIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getIndex())

@handler("TimeDifferencesND.setMaxRollovers")
def _m_TimeDifferencesND_setMaxRollovers(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.setMaxRollovers(params[1])

@handler("TimeDifferencesND.getHistogramIndex")
def _m_TimeDifferencesND_getHistogramIndex(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getHistogramIndex())

@handler("TimeDifferencesND.getRollovers")
def _m_TimeDifferencesND_getRollovers(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getRollovers())

@handler("TimeTagStream.getData")
def _m_TimeTagStream_getData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    result = obj.getData()
    return _register(result, 'TimeTagStreamBuffer', ctx.session_id, ctx.registry, ctx.sessions)

@handler("TimeTagStream.getCounts")
def _m_TimeTagStream_getCounts(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getCounts()

@handler("TimeTagStreamBuffer.getTimestamps")
def _m_TimeTagStreamBuffer_getTimestamps(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getTimestamps())

@handler("TimeTagStreamBuffer.getChannels")
def _m_TimeTagStreamBuffer_getChannels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getChannels())

@handler("TimeTagStreamBuffer.getOverflows")
def _m_TimeTagStreamBuffer_getOverflows(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getOverflows())

@handler("TimeTagStreamBuffer.getEventTypes")
def _m_TimeTagStreamBuffer_getEventTypes(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getEventTypes())

@handler("TimeTagStreamBuffer.getMissedEvents")
def _m_TimeTagStreamBuffer_getMissedEvents(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return _pack_ndarray(obj.getMissedEvents())

@handler("TimeTagStreamBuffer.size")
def _m_TimeTagStreamBuffer_size(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.size()

@handler("TimeTagStreamBuffer.hasOverflows")
def _m_TimeTagStreamBuffer_hasOverflows(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.hasOverflows()

@handler("TimeTagStreamBuffer.tStart")
def _m_TimeTagStreamBuffer_tStart(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.tStart()

@handler("TimeTagStreamBuffer.tGetData")
def _m_TimeTagStreamBuffer_tGetData(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.tGetData()

@handler("TimeTagStreamBuffer.discard")
def _m_TimeTagStreamBuffer_discard(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.discard()

@handler("TriggerOnCountrate.getChannelAbove")
def _m_TriggerOnCountrate_getChannelAbove(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannelAbove()

@handler("TriggerOnCountrate.getChannelBelow")
def _m_TriggerOnCountrate_getChannelBelow(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannelBelow()

@handler("TriggerOnCountrate.getChannels")
def _m_TriggerOnCountrate_getChannels(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getChannels()

@handler("TriggerOnCountrate.getCurrentCountrate")
def _m_TriggerOnCountrate_getCurrentCountrate(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.getCurrentCountrate()

@handler("TriggerOnCountrate.injectCurrentState")
def _m_TriggerOnCountrate_injectCurrentState(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.injectCurrentState()

@handler("TriggerOnCountrate.isAbove")
def _m_TriggerOnCountrate_isAbove(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.isAbove()

@handler("TriggerOnCountrate.isBelow")
def _m_TriggerOnCountrate_isBelow(ctx: HandlerContext, params):
    obj = _lookup(ctx.registry, params[0])
    return obj.isBelow()
