import enum as _enum
import types
from _typeshed import Incomplete

class _SwigNonDynamicMeta(type):
    __setattr__: Incomplete

class SwigPyIterator:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def value(self) -> 'PyObject *': ...
    def incr(self, n: size_t = 1) -> 'swig::SwigPyIterator *': ...
    def decr(self, n: size_t = 1) -> 'swig::SwigPyIterator *': ...
    def distance(self, x: SwigPyIterator) -> ptrdiff_t: ...
    def equal(self, x: SwigPyIterator) -> bool: ...
    def copy(self) -> 'swig::SwigPyIterator *': ...
    def next(self) -> 'PyObject *': ...
    def __next__(self) -> 'PyObject *': ...
    def previous(self) -> 'PyObject *': ...
    def advance(self, n: ptrdiff_t) -> 'swig::SwigPyIterator *': ...
    def __eq__(self, x: SwigPyIterator) -> bool: ...
    def __ne__(self, x: SwigPyIterator) -> bool: ...
    def __iadd__(self, n: ptrdiff_t) -> 'swig::SwigPyIterator &': ...
    def __isub__(self, n: ptrdiff_t) -> 'swig::SwigPyIterator &': ...
    def __add__(self, n: ptrdiff_t) -> 'swig::SwigPyIterator *': ...
    def __sub__(self, *args) -> ptrdiff_t: ...
    def __iter__(self): ...

SHARED_PTR_DISOWN: Incomplete

class _CharVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< signed char >::size_type': ...
    def __getslice__(self, i: 'std::vector< signed char >::difference_type', j: 'std::vector< signed char >::difference_type') -> 'std::vector< signed char,std::allocator< signed char > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< signed char >::difference_type', j: 'std::vector< signed char >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< signed char >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< signed char >::value_type': ...
    def append(self, x: 'std::vector< signed char >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< signed char >::size_type': ...
    def swap(self, v: _CharVector) -> void: ...
    def begin(self) -> 'std::vector< signed char >::iterator': ...
    def end(self) -> 'std::vector< signed char >::iterator': ...
    def rbegin(self) -> 'std::vector< signed char >::reverse_iterator': ...
    def rend(self) -> 'std::vector< signed char >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< signed char >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< signed char >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< signed char >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< signed char >::value_type const &': ...
    def back(self) -> 'std::vector< signed char >::value_type const &': ...
    def assign(self, n: 'std::vector< signed char >::size_type', x: 'std::vector< signed char >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< signed char >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< signed char >::size_type': ...
    __swig_destroy__: Incomplete

class _UCharVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< unsigned char >::size_type': ...
    def __getslice__(self, i: 'std::vector< unsigned char >::difference_type', j: 'std::vector< unsigned char >::difference_type') -> 'std::vector< unsigned char,std::allocator< unsigned char > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< unsigned char >::difference_type', j: 'std::vector< unsigned char >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< unsigned char >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< unsigned char >::value_type': ...
    def append(self, x: 'std::vector< unsigned char >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< unsigned char >::size_type': ...
    def swap(self, v: _UCharVector) -> void: ...
    def begin(self) -> 'std::vector< unsigned char >::iterator': ...
    def end(self) -> 'std::vector< unsigned char >::iterator': ...
    def rbegin(self) -> 'std::vector< unsigned char >::reverse_iterator': ...
    def rend(self) -> 'std::vector< unsigned char >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< unsigned char >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< unsigned char >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< unsigned char >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< unsigned char >::value_type const &': ...
    def back(self) -> 'std::vector< unsigned char >::value_type const &': ...
    def assign(self, n: 'std::vector< unsigned char >::size_type', x: 'std::vector< unsigned char >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< unsigned char >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< unsigned char >::size_type': ...
    __swig_destroy__: Incomplete

class _ShortVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< short >::size_type': ...
    def __getslice__(self, i: 'std::vector< short >::difference_type', j: 'std::vector< short >::difference_type') -> 'std::vector< short,std::allocator< short > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< short >::difference_type', j: 'std::vector< short >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< short >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< short >::value_type': ...
    def append(self, x: 'std::vector< short >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< short >::size_type': ...
    def swap(self, v: _ShortVector) -> void: ...
    def begin(self) -> 'std::vector< short >::iterator': ...
    def end(self) -> 'std::vector< short >::iterator': ...
    def rbegin(self) -> 'std::vector< short >::reverse_iterator': ...
    def rend(self) -> 'std::vector< short >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< short >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< short >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< short >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< short >::value_type const &': ...
    def back(self) -> 'std::vector< short >::value_type const &': ...
    def assign(self, n: 'std::vector< short >::size_type', x: 'std::vector< short >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< short >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< short >::size_type': ...
    __swig_destroy__: Incomplete

class _UShortVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< unsigned short >::size_type': ...
    def __getslice__(self, i: 'std::vector< unsigned short >::difference_type', j: 'std::vector< unsigned short >::difference_type') -> 'std::vector< unsigned short,std::allocator< unsigned short > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< unsigned short >::difference_type', j: 'std::vector< unsigned short >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< unsigned short >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< unsigned short >::value_type': ...
    def append(self, x: 'std::vector< unsigned short >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< unsigned short >::size_type': ...
    def swap(self, v: _UShortVector) -> void: ...
    def begin(self) -> 'std::vector< unsigned short >::iterator': ...
    def end(self) -> 'std::vector< unsigned short >::iterator': ...
    def rbegin(self) -> 'std::vector< unsigned short >::reverse_iterator': ...
    def rend(self) -> 'std::vector< unsigned short >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< unsigned short >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< unsigned short >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< unsigned short >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< unsigned short >::value_type const &': ...
    def back(self) -> 'std::vector< unsigned short >::value_type const &': ...
    def assign(self, n: 'std::vector< unsigned short >::size_type', x: 'std::vector< unsigned short >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< unsigned short >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< unsigned short >::size_type': ...
    __swig_destroy__: Incomplete

class _IntVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< int >::size_type': ...
    def __getslice__(self, i: 'std::vector< int >::difference_type', j: 'std::vector< int >::difference_type') -> 'std::vector< int,std::allocator< int > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< int >::difference_type', j: 'std::vector< int >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< int >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< int >::value_type': ...
    def append(self, x: 'std::vector< int >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< int >::size_type': ...
    def swap(self, v: _IntVector) -> void: ...
    def begin(self) -> 'std::vector< int >::iterator': ...
    def end(self) -> 'std::vector< int >::iterator': ...
    def rbegin(self) -> 'std::vector< int >::reverse_iterator': ...
    def rend(self) -> 'std::vector< int >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< int >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< int >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< int >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< int >::value_type const &': ...
    def back(self) -> 'std::vector< int >::value_type const &': ...
    def assign(self, n: 'std::vector< int >::size_type', x: 'std::vector< int >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< int >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< int >::size_type': ...
    __swig_destroy__: Incomplete

class _UIntVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< unsigned int >::size_type': ...
    def __getslice__(self, i: 'std::vector< unsigned int >::difference_type', j: 'std::vector< unsigned int >::difference_type') -> 'std::vector< unsigned int,std::allocator< unsigned int > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< unsigned int >::difference_type', j: 'std::vector< unsigned int >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< unsigned int >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< unsigned int >::value_type': ...
    def append(self, x: 'std::vector< unsigned int >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< unsigned int >::size_type': ...
    def swap(self, v: _UIntVector) -> void: ...
    def begin(self) -> 'std::vector< unsigned int >::iterator': ...
    def end(self) -> 'std::vector< unsigned int >::iterator': ...
    def rbegin(self) -> 'std::vector< unsigned int >::reverse_iterator': ...
    def rend(self) -> 'std::vector< unsigned int >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< unsigned int >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< unsigned int >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< unsigned int >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< unsigned int >::value_type const &': ...
    def back(self) -> 'std::vector< unsigned int >::value_type const &': ...
    def assign(self, n: 'std::vector< unsigned int >::size_type', x: 'std::vector< unsigned int >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< unsigned int >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< unsigned int >::size_type': ...
    __swig_destroy__: Incomplete

class _LongVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< long >::size_type': ...
    def __getslice__(self, i: 'std::vector< long >::difference_type', j: 'std::vector< long >::difference_type') -> 'std::vector< long,std::allocator< long > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< long >::difference_type', j: 'std::vector< long >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< long >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< long >::value_type': ...
    def append(self, x: 'std::vector< long >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< long >::size_type': ...
    def swap(self, v: _LongVector) -> void: ...
    def begin(self) -> 'std::vector< long >::iterator': ...
    def end(self) -> 'std::vector< long >::iterator': ...
    def rbegin(self) -> 'std::vector< long >::reverse_iterator': ...
    def rend(self) -> 'std::vector< long >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< long >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< long >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< long >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< long >::value_type const &': ...
    def back(self) -> 'std::vector< long >::value_type const &': ...
    def assign(self, n: 'std::vector< long >::size_type', x: 'std::vector< long >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< long >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< long >::size_type': ...
    __swig_destroy__: Incomplete

class _ULongVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< unsigned long >::size_type': ...
    def __getslice__(self, i: 'std::vector< unsigned long >::difference_type', j: 'std::vector< unsigned long >::difference_type') -> 'std::vector< unsigned long,std::allocator< unsigned long > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< unsigned long >::difference_type', j: 'std::vector< unsigned long >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< unsigned long >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< unsigned long >::value_type': ...
    def append(self, x: 'std::vector< unsigned long >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< unsigned long >::size_type': ...
    def swap(self, v: _ULongVector) -> void: ...
    def begin(self) -> 'std::vector< unsigned long >::iterator': ...
    def end(self) -> 'std::vector< unsigned long >::iterator': ...
    def rbegin(self) -> 'std::vector< unsigned long >::reverse_iterator': ...
    def rend(self) -> 'std::vector< unsigned long >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< unsigned long >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< unsigned long >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< unsigned long >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< unsigned long >::value_type const &': ...
    def back(self) -> 'std::vector< unsigned long >::value_type const &': ...
    def assign(self, n: 'std::vector< unsigned long >::size_type', x: 'std::vector< unsigned long >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< unsigned long >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< unsigned long >::size_type': ...
    __swig_destroy__: Incomplete

class _LongLongVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< long long >::size_type': ...
    def __getslice__(self, i: 'std::vector< long long >::difference_type', j: 'std::vector< long long >::difference_type') -> 'std::vector< long long,std::allocator< long long > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< long long >::difference_type', j: 'std::vector< long long >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< long long >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< long long >::value_type': ...
    def append(self, x: 'std::vector< long long >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< long long >::size_type': ...
    def swap(self, v: _LongLongVector) -> void: ...
    def begin(self) -> 'std::vector< long long >::iterator': ...
    def end(self) -> 'std::vector< long long >::iterator': ...
    def rbegin(self) -> 'std::vector< long long >::reverse_iterator': ...
    def rend(self) -> 'std::vector< long long >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< long long >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< long long >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< long long >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< long long >::value_type const &': ...
    def back(self) -> 'std::vector< long long >::value_type const &': ...
    def assign(self, n: 'std::vector< long long >::size_type', x: 'std::vector< long long >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< long long >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< long long >::size_type': ...
    __swig_destroy__: Incomplete

class _ULongLongVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< unsigned long long >::size_type': ...
    def __getslice__(self, i: 'std::vector< unsigned long long >::difference_type', j: 'std::vector< unsigned long long >::difference_type') -> 'std::vector< unsigned long long,std::allocator< unsigned long long > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< unsigned long long >::difference_type', j: 'std::vector< unsigned long long >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< unsigned long long >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< unsigned long long >::value_type': ...
    def append(self, x: 'std::vector< unsigned long long >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< unsigned long long >::size_type': ...
    def swap(self, v: _ULongLongVector) -> void: ...
    def begin(self) -> 'std::vector< unsigned long long >::iterator': ...
    def end(self) -> 'std::vector< unsigned long long >::iterator': ...
    def rbegin(self) -> 'std::vector< unsigned long long >::reverse_iterator': ...
    def rend(self) -> 'std::vector< unsigned long long >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< unsigned long long >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< unsigned long long >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< unsigned long long >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< unsigned long long >::value_type const &': ...
    def back(self) -> 'std::vector< unsigned long long >::value_type const &': ...
    def assign(self, n: 'std::vector< unsigned long long >::size_type', x: 'std::vector< unsigned long long >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< unsigned long long >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< unsigned long long >::size_type': ...
    __swig_destroy__: Incomplete

class _FloatVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< float >::size_type': ...
    def __getslice__(self, i: 'std::vector< float >::difference_type', j: 'std::vector< float >::difference_type') -> 'std::vector< float,std::allocator< float > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< float >::difference_type', j: 'std::vector< float >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< float >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< float >::value_type': ...
    def append(self, x: 'std::vector< float >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< float >::size_type': ...
    def swap(self, v: _FloatVector) -> void: ...
    def begin(self) -> 'std::vector< float >::iterator': ...
    def end(self) -> 'std::vector< float >::iterator': ...
    def rbegin(self) -> 'std::vector< float >::reverse_iterator': ...
    def rend(self) -> 'std::vector< float >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< float >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< float >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< float >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< float >::value_type const &': ...
    def back(self) -> 'std::vector< float >::value_type const &': ...
    def assign(self, n: 'std::vector< float >::size_type', x: 'std::vector< float >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< float >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< float >::size_type': ...
    __swig_destroy__: Incomplete

class _DoubleVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< double >::size_type': ...
    def __getslice__(self, i: 'std::vector< double >::difference_type', j: 'std::vector< double >::difference_type') -> 'std::vector< double,std::allocator< double > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< double >::difference_type', j: 'std::vector< double >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< double >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< double >::value_type': ...
    def append(self, x: 'std::vector< double >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< double >::size_type': ...
    def swap(self, v: _DoubleVector) -> void: ...
    def begin(self) -> 'std::vector< double >::iterator': ...
    def end(self) -> 'std::vector< double >::iterator': ...
    def rbegin(self) -> 'std::vector< double >::reverse_iterator': ...
    def rend(self) -> 'std::vector< double >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< double >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< double >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< double >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< double >::value_type const &': ...
    def back(self) -> 'std::vector< double >::value_type const &': ...
    def assign(self, n: 'std::vector< double >::size_type', x: 'std::vector< double >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< double >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< double >::size_type': ...
    __swig_destroy__: Incomplete

class _StringVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< std::string >::size_type': ...
    def __getslice__(self, i: 'std::vector< std::string >::difference_type', j: 'std::vector< std::string >::difference_type') -> 'std::vector< std::string,std::allocator< std::string > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< std::string >::difference_type', j: 'std::vector< std::string >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< std::string >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< std::string >::value_type': ...
    def append(self, x: 'std::vector< std::string >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< std::string >::size_type': ...
    def swap(self, v: _StringVector) -> void: ...
    def begin(self) -> 'std::vector< std::string >::iterator': ...
    def end(self) -> 'std::vector< std::string >::iterator': ...
    def rbegin(self) -> 'std::vector< std::string >::reverse_iterator': ...
    def rend(self) -> 'std::vector< std::string >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< std::string >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< std::string >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< std::string >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< std::string >::value_type const &': ...
    def back(self) -> 'std::vector< std::string >::value_type const &': ...
    def assign(self, n: 'std::vector< std::string >::size_type', x: 'std::vector< std::string >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< std::string >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< std::string >::size_type': ...
    __swig_destroy__: Incomplete

class _EventVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< Event >::size_type': ...
    def __getslice__(self, i: 'std::vector< Event >::difference_type', j: 'std::vector< Event >::difference_type') -> 'std::vector< Event,std::allocator< Event > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< Event >::difference_type', j: 'std::vector< Event >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< Event >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< Event >::value_type': ...
    def append(self, x: Event) -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< Event >::size_type': ...
    def swap(self, v: _EventVector) -> void: ...
    def begin(self) -> 'std::vector< Event >::iterator': ...
    def end(self) -> 'std::vector< Event >::iterator': ...
    def rbegin(self) -> 'std::vector< Event >::reverse_iterator': ...
    def rend(self) -> 'std::vector< Event >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< Event >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< Event >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: Event) -> void: ...
    def front(self) -> 'std::vector< Event >::value_type const &': ...
    def back(self) -> 'std::vector< Event >::value_type const &': ...
    def assign(self, n: 'std::vector< Event >::size_type', x: Event) -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< Event >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< Event >::size_type': ...
    __swig_destroy__: Incomplete

class _TimeTaggerServerVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::size_type': ...
    def __getslice__(self, i: 'std::vector< std::shared_ptr< TimeTaggerServer > >::difference_type', j: 'std::vector< std::shared_ptr< TimeTaggerServer > >::difference_type') -> 'std::vector< std::shared_ptr< TimeTaggerServer >,std::allocator< std::shared_ptr< TimeTaggerServer > > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< std::shared_ptr< TimeTaggerServer > >::difference_type', j: 'std::vector< std::shared_ptr< TimeTaggerServer > >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::value_type': ...
    def append(self, x: 'std::vector< std::shared_ptr< TimeTaggerServer > >::value_type const &') -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::size_type': ...
    def swap(self, v: _TimeTaggerServerVector) -> void: ...
    def begin(self) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::iterator': ...
    def end(self) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::iterator': ...
    def rbegin(self) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::reverse_iterator': ...
    def rend(self) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: 'std::vector< std::shared_ptr< TimeTaggerServer > >::value_type const &') -> void: ...
    def front(self) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::value_type const &': ...
    def back(self) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::value_type const &': ...
    def assign(self, n: 'std::vector< std::shared_ptr< TimeTaggerServer > >::size_type', x: 'std::vector< std::shared_ptr< TimeTaggerServer > >::value_type const &') -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< std::shared_ptr< TimeTaggerServer > >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< std::shared_ptr< TimeTaggerServer > >::size_type': ...
    __swig_destroy__: Incomplete

class _IntVectorVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< std::vector< int > >::size_type': ...
    def __getslice__(self, i: 'std::vector< std::vector< int > >::difference_type', j: 'std::vector< std::vector< int > >::difference_type') -> 'std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< std::vector< int > >::difference_type', j: 'std::vector< std::vector< int > >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< std::vector< int > >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< std::vector< int > >::value_type': ...
    def append(self, x: _IntVector) -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< std::vector< int > >::size_type': ...
    def swap(self, v: _IntVectorVector) -> void: ...
    def begin(self) -> 'std::vector< std::vector< int > >::iterator': ...
    def end(self) -> 'std::vector< std::vector< int > >::iterator': ...
    def rbegin(self) -> 'std::vector< std::vector< int > >::reverse_iterator': ...
    def rend(self) -> 'std::vector< std::vector< int > >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< std::vector< int > >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< std::vector< int > >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: _IntVector) -> void: ...
    def front(self) -> 'std::vector< std::vector< int > >::value_type const &': ...
    def back(self) -> 'std::vector< std::vector< int > >::value_type const &': ...
    def assign(self, n: 'std::vector< std::vector< int > >::size_type', x: _IntVector) -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< std::vector< int > >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< std::vector< int > >::size_type': ...
    __swig_destroy__: Incomplete

class _EventVectorVector:
    thisown: Incomplete
    def iterator(self) -> 'swig::SwigPyIterator *': ...
    def __iter__(self): ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> 'std::vector< std::vector< Event > >::size_type': ...
    def __getslice__(self, i: 'std::vector< std::vector< Event > >::difference_type', j: 'std::vector< std::vector< Event > >::difference_type') -> 'std::vector< std::vector< Event,std::allocator< Event > >,std::allocator< std::vector< Event,std::allocator< Event > > > > *': ...
    def __setslice__(self, *args) -> void: ...
    def __delslice__(self, i: 'std::vector< std::vector< Event > >::difference_type', j: 'std::vector< std::vector< Event > >::difference_type') -> void: ...
    def __delitem__(self, *args) -> void: ...
    def __getitem__(self, *args) -> 'std::vector< std::vector< Event > >::value_type const &': ...
    def __setitem__(self, *args) -> void: ...
    def pop(self) -> 'std::vector< std::vector< Event > >::value_type': ...
    def append(self, x: _EventVector) -> void: ...
    def empty(self) -> bool: ...
    def size(self) -> 'std::vector< std::vector< Event > >::size_type': ...
    def swap(self, v: _EventVectorVector) -> void: ...
    def begin(self) -> 'std::vector< std::vector< Event > >::iterator': ...
    def end(self) -> 'std::vector< std::vector< Event > >::iterator': ...
    def rbegin(self) -> 'std::vector< std::vector< Event > >::reverse_iterator': ...
    def rend(self) -> 'std::vector< std::vector< Event > >::reverse_iterator': ...
    def clear(self) -> void: ...
    def get_allocator(self) -> 'std::vector< std::vector< Event > >::allocator_type': ...
    def pop_back(self) -> void: ...
    def erase(self, *args) -> 'std::vector< std::vector< Event > >::iterator': ...
    def __init__(self, *args) -> None: ...
    def push_back(self, x: _EventVector) -> void: ...
    def front(self) -> 'std::vector< std::vector< Event > >::value_type const &': ...
    def back(self) -> 'std::vector< std::vector< Event > >::value_type const &': ...
    def assign(self, n: 'std::vector< std::vector< Event > >::size_type', x: _EventVector) -> void: ...
    def resize(self, *args) -> void: ...
    def insert(self, *args) -> void: ...
    def reserve(self, n: 'std::vector< std::vector< Event > >::size_type') -> void: ...
    def capacity(self) -> 'std::vector< std::vector< Event > >::size_type': ...
    __swig_destroy__: Incomplete

def getVersion() -> 'std::string': ...
def getCompilerVersion() -> 'std::string': ...
def getCompilationTimestamp() -> int64_t: ...

Resolution_Standard: Incomplete
Resolution_HighResA: Incomplete
Resolution_HighResB: Incomplete
Resolution_HighResC: Incomplete
ChannelEdge_All: Incomplete
ChannelEdge_Rising: Incomplete
ChannelEdge_Falling: Incomplete
ChannelEdge_HighResAll: Incomplete
ChannelEdge_HighResRising: Incomplete
ChannelEdge_HighResFalling: Incomplete
ChannelEdge_StandardAll: Incomplete
ChannelEdge_StandardRising: Incomplete
ChannelEdge_StandardFalling: Incomplete

class SoftwareClockState:
    thisown: Incomplete
    clock_period: 'long long'
    input_channel: int
    ideal_clock_channel: int
    averaging_periods: double
    enabled: bool
    is_locked: bool
    error_counter: uint32_t
    last_ideal_clock_event: 'long long'
    period_error: double
    phase_error_estimation: double
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

cvar: Incomplete
CHANNEL_UNUSED: Incomplete
CHANNEL_UNUSED_OLD: Incomplete
TT_CHANNEL_NUMBER_SCHEME_AUTO: Incomplete
TT_CHANNEL_NUMBER_SCHEME_ZERO: Incomplete
TT_CHANNEL_NUMBER_SCHEME_ONE: Incomplete
TT_CHANNEL_NUMBER_SCHEME_DEFAULT: Incomplete
TT_CHANNEL_RISING_AND_FALLING_EDGES: Incomplete
TT_CHANNEL_RISING_EDGES: Incomplete
TT_CHANNEL_FALLING_EDGES: Incomplete

class ReferenceClockState:
    thisown: Incomplete
    clock_period: 'long long'
    clock_channel: int
    synchronization_channel: int
    ideal_clock_channel: int
    averaging_periods: double
    synchronization_offset: 'long long'
    enabled: bool
    event_divider: int
    is_locked: bool
    is_synchronized: bool
    error_counter: uint32_t
    last_ideal_clock_event: 'long long'
    period_error: double
    phase_error_estimation: double
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

FpgaLinkInterface_SFPP_10GE: Incomplete
FpgaLinkInterface_QSFPP_40GE: Incomplete

def createTimeTagger(*args, **kwargs) -> TimeTagger: ...
def createTimeTaggerVirtual(*args, **kwargs) -> TimeTaggerVirtual: ...
def createTimeTaggerNetwork(*args) -> TimeTaggerNetwork: ...
def setCustomBitFileName(bitFileName: 'std::string const &') -> void: ...
def scanTimeTagger(include_model_name: bool = False) -> 'std::vector< std::string,std::allocator< std::string > >': ...
def getTimeTaggerServerInfo(*args, **kwargs) -> 'std::string': ...
def scanTimeTaggerServers() -> 'std::vector< std::string,std::allocator< std::string > >': ...
def getTimeTaggerModel(serial: 'std::string const &') -> 'std::string': ...
def setTimeTaggerChannelNumberScheme(scheme: int) -> void: ...
def getTimeTaggerChannelNumberScheme() -> int: ...
def hasTimeTaggerVirtualLicense() -> bool: ...
def flashLicense(serial: 'std::string const &', license: 'std::string const &') -> void: ...
def extractDeviceLicense(license: 'std::string const &') -> 'std::string': ...

LOGGER_ERROR: Incomplete
LOGGER_WARNING: Incomplete
LOGGER_INFO: Incomplete

class CustomLogger:
    thisown: Incomplete
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete
    def enable(self) -> void: ...
    def disable(self) -> void: ...
    def Log(self, level: int, msg: 'std::string const &') -> void: ...
    def __disown__(self): ...

def checkSystemLibraries() -> void: ...

class TimeTaggerSource:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def setInputDelay(self, channel: int, delay: 'long long') -> void: ...
    def getInputDelay(self, channel: int) -> 'long long': ...
    def setDelayHardware(self, channel: int, delay: 'long long') -> void: ...
    def getDelayHardware(self, channel: int) -> 'long long': ...
    def getDelayHardwareRange(self, channel: int) -> 'std::vector< long long,std::allocator< long long > >': ...
    def setDelaySoftware(self, channel: int, delay: 'long long') -> void: ...
    def getDelaySoftware(self, channel: int) -> 'long long': ...
    def setDeadtime(self, channel: int, deadtime: 'long long') -> 'long long': ...
    def getDeadtime(self, channel: int) -> 'long long': ...
    def getDeadtimeRange(self, channel: int) -> 'std::vector< long long,std::allocator< long long > >': ...
    def setConditionalFilter(self, trigger: _IntVector, filtered: _IntVector) -> void: ...
    def clearConditionalFilter(self) -> void: ...
    def getConditionalFilterTrigger(self) -> 'std::vector< int,std::allocator< int > >': ...
    def getConditionalFilterFiltered(self) -> 'std::vector< int,std::allocator< int > >': ...
    def setEventDivider(self, channel: int, divider: 'unsigned int') -> void: ...
    def getEventDivider(self, channel: int) -> 'unsigned int': ...
    def getOverflows(self) -> 'long long': ...
    def getOverflowsAndClear(self) -> 'long long': ...
    def clearOverflows(self) -> void: ...
    def setReferenceClock(self, *args, **kwargs) -> void: ...
    def disableReferenceClock(self) -> void: ...
    def getReferenceClockState(self) -> ReferenceClockState: ...
    __swig_destroy__: Incomplete

class TimeTaggerBase(TimeTaggerSource):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def setSoftwareClock(self, input_channel: int, input_frequency: double = 10000000.0, averaging_periods: double = 1000, wait_until_locked: bool = True) -> void: ...
    def disableSoftwareClock(self) -> void: ...
    def getSoftwareClockState(self) -> SoftwareClockState: ...
    def getFence(self, alloc_fence: bool = True) -> 'unsigned int': ...
    def getInvertedChannel(self, channel: int) -> int: ...
    def isUnusedChannel(self, channel: int) -> bool: ...
    def getConfiguration(self) -> 'std::string': ...
    def getRegistrations(self, channel: int) -> int: ...
    def isChannelRegistered(self, channel: int) -> bool: ...
    def xtra_setAutoStart(self, auto_start: bool) -> void: ...
    def xtra_getAutoStart(self) -> bool: ...
    __swig_destroy__: Incomplete
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...
    def sync(self, timeout: int = -1): ...
    def waitForFence(self, fence, timeout: int = -1): ...

class TimeTaggerHardware:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def setTriggerLevel(self, channel: int, voltage: double) -> void: ...
    def getTriggerLevel(self, channel: int) -> double: ...
    def getHardwareDelayCompensation(self, channel: int) -> 'long long': ...
    def setHardwareDelayCompensationActive(self, use_compensation: bool) -> void: ...
    def setInputImpedanceHigh(self, channel: int, high_impedance: bool) -> void: ...
    def getInputImpedanceHigh(self, channel: int) -> bool: ...
    def setInputHysteresis(self, channel: int, value: int) -> void: ...
    def getInputHysteresis(self, channel: int) -> int: ...
    def setNormalization(self, channels: _IntVector, state: bool) -> void: ...
    def getNormalization(self, channel: int) -> bool: ...
    def getSerial(self) -> 'std::string': ...
    def getModel(self) -> 'std::string': ...
    def getPcbVersion(self) -> 'std::string': ...
    def getFirmwareVersion(self) -> 'std::string': ...
    def getDACRange(self) -> 'std::vector< double,std::allocator< double > >': ...
    def getTriggerLevelRange(self, channel: int) -> 'std::vector< double,std::allocator< double > >': ...
    def getChannelList(self, *args, **kwargs) -> 'std::vector< int,std::allocator< int > >': ...
    def setHardwareBufferSize(self, size: int) -> void: ...
    def getHardwareBufferSize(self) -> int: ...
    def getPsPerClock(self) -> 'long long': ...
    def setStreamBlockSize(self, max_events: int, max_latency: int) -> void: ...
    def getStreamBlockSizeEvents(self) -> int: ...
    def getStreamBlockSizeLatency(self) -> int: ...
    def setTestSignal(self, *args) -> void: ...
    def getTestSignal(self, channel: int) -> bool: ...
    def setTestSignalDivider(self, divider: int) -> void: ...
    def getTestSignalDivider(self) -> int: ...
    def getDeviceLicense(self) -> 'std::string': ...
    def getSensorData(self) -> 'std::string': ...
    def disableLEDs(self, disabled: bool) -> void: ...
    def setLED(self, bitmask: uint32_t) -> void: ...
    def setSoundFrequency(self, freq_hz: uint32_t) -> void: ...
    def setTimeTaggerNetworkStreamCompression(self, active: bool) -> void: ...
    def getChannelNumberScheme(self) -> int: ...
    __swig_destroy__: Incomplete

class TimeTaggerVirtual(TimeTaggerBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def run(self, speed: double = -1.0) -> 'std::vector< uint64_t,std::allocator< uint64_t > >': ...
    def replay(self, file: 'std::string const &', begin: 'long long' = 0, duration: 'long long' = -1, queue: bool = True) -> uint64_t: ...
    def stop(self) -> void: ...
    def appendFile(self, filename: 'std::string const &', begin: 'long long' = 0, duration: 'long long' = -1, clear: bool = False) -> uint64_t: ...
    def setReplaySpeed(self, speed: double) -> void: ...
    def getReplaySpeed(self) -> double: ...
    def reset(self) -> void: ...
    def getChannelList(self) -> 'std::vector< int,std::allocator< int > >': ...
    def setTestSignal(self, *args) -> void: ...
    def getTestSignal(self, channel: int) -> bool: ...
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...
    def waitForCompletion(self, ID: int = 0, timeout: int = -1): ...
    def waitUntilFinished(self, ID: int = 0, timeout: int = -1): ...
    __swig_destroy__: Incomplete

AccessMode_Listen: Incomplete
AccessMode_SynchronousListen: Incomplete
AccessMode_Control: Incomplete
AccessMode_SynchronousControl: Incomplete

class TimeTaggerServer(TimeTaggerHardware, TimeTaggerSource):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def getAddress(self) -> 'std::string': ...
    def getAccessMode(self) -> AccessMode: ...
    def getClientChannel(self, server_channel: int) -> int: ...
    __swig_destroy__: Incomplete
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...

class TimeTaggerNetwork(TimeTaggerBase, TimeTaggerHardware):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def isConnected(self) -> bool: ...
    def setDelayClient(self, channel: int, time: 'long long') -> void: ...
    def getDelayClient(self, channel: int) -> 'long long': ...
    def getOverflowsClient(self) -> 'long long': ...
    def getOverflowsAndClearClient(self) -> 'long long': ...
    def clearOverflowsClient(self) -> void: ...
    def getServer(self, ip_address: 'std::string') -> TimeTaggerServer: ...
    def getServers(self) -> list[TimeTaggerServer]: ...
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...
    __swig_destroy__: Incomplete

class TimeTagger(TimeTaggerBase, TimeTaggerHardware):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def reset(self) -> void: ...
    def autoCalibration(self) -> void: ...
    def getDistributionCount(self) -> void: ...
    def getDistributionPSecs(self) -> void: ...
    def enableFpgaLink(self, *args, **kwargs) -> void: ...
    def disableFpgaLink(self) -> void: ...
    def startServer(self, *args, **kwargs) -> void: ...
    def stopServer(self) -> void: ...
    def isServerRunning(self) -> bool: ...
    def setServerAddress(self, ip_address: 'std::string') -> void: ...
    def getServerAddress(self) -> 'std::string': ...
    def getConnectedClients(self) -> 'std::vector< std::string,std::allocator< std::string > >': ...
    def xtra_setAvgRisingFalling(self, channel: int, enable: bool) -> void: ...
    def xtra_getAvgRisingFalling(self, channel: int) -> bool: ...
    def xtra_setHighPrioChannel(self, channel: int, enable: bool) -> void: ...
    def xtra_getHighPrioChannel(self, channel: int) -> bool: ...
    def xtra_setAuxOut(self, channel: int, enabled: bool) -> void: ...
    def xtra_getAuxOut(self, channel: int) -> bool: ...
    def xtra_setAuxOutSignal(self, channel: int, divider: int, duty_cycle: double = 0.5) -> void: ...
    def xtra_getAuxOutSignalDivider(self, channel: int) -> int: ...
    def xtra_getAuxOutSignalDutyCycle(self, channel: int) -> double: ...
    def xtra_measureTriggerLevel(self, channel: int) -> double: ...
    def xtra_setClockSource(self, source: int) -> void: ...
    def xtra_getClockSource(self) -> int: ...
    def xtra_setClockAutoSelect(self, enabled: bool) -> void: ...
    def xtra_getClockAutoSelect(self) -> bool: ...
    def xtra_setClockOut(self, enabled: bool) -> void: ...
    def xtra_setFanSpeed(self, percentage: double = -1) -> void: ...
    def setInputMux(self, channel: int, mux_mode: int) -> void: ...
    def getInputMux(self, channel: int) -> int: ...
    def factoryAccess(self, pw: uint32_t, addr: uint32_t, data: uint32_t, mask: uint32_t, use_wb: bool = False) -> uint32_t: ...
    def updateBMCFirmware(self, firmware: 'std::string const &') -> void: ...
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...
    __swig_destroy__: Incomplete

class Tag:
    thisown: Incomplete
    Type_TimeTag: Incomplete
    Type_Error: Incomplete
    Type_OverflowBegin: Incomplete
    Type_OverflowEnd: Incomplete
    Type_MissedEvents: Incomplete
    type: 'Tag::Type'
    reserved: char
    missed_events: 'unsigned short'
    channel: int
    time: 'long long'
    def __init__(self, *args) -> None: ...
    __swig_destroy__: Incomplete

class IteratorBase:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def clear(self) -> void: ...
    def start(self) -> void: ...
    def startFor(self, capture_duration: 'long long', clear: bool = True) -> void: ...
    def stop(self) -> void: ...
    def abort(self) -> void: ...
    def isRunning(self) -> bool: ...
    def getCaptureDuration(self) -> 'long long': ...
    def getConfiguration(self) -> 'std::string': ...
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...
    def waitUntilFinished(self, timeout: int = -1): ...

LanguageUsed_Cpp: Incomplete
LanguageUsed_Python: Incomplete
LanguageUsed_Csharp: Incomplete
LanguageUsed_Matlab: Incomplete
LanguageUsed_Labview: Incomplete
LanguageUsed_Mathematica: Incomplete
LanguageUsed_Unknown: Incomplete
FrontendType_Undefined: Incomplete
FrontendType_WebApp: Incomplete
FrontendType_Firefly: Incomplete
FrontendType_Pyro5RPC: Incomplete
FrontendType_UserFrontend: Incomplete
FrontendType_DLScat: Incomplete

def setLanguageInfo(pw: 'std::uint32_t', language: LanguageUsed, version: 'std::string') -> void: ...
def setFrontend(frontend: FrontendType) -> void: ...

UsageStatisticsStatus_Disabled: Incomplete
UsageStatisticsStatus_Collecting: Incomplete
UsageStatisticsStatus_CollectingAndUploading: Incomplete

def setUsageStatisticsStatus(new_status: UsageStatisticsStatus) -> void: ...
def getUsageStatisticsStatus() -> UsageStatisticsStatus: ...
def getUsageStatisticsReport() -> 'std::string': ...
def mergeStreamFiles(output_filename: 'std::string const &', input_filenames: _StringVector, channel_offsets: _IntVector, time_offsets: _LongLongVector, overlap_only: bool) -> void: ...

class ChannelGate:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    gate_open_channel: 'int const'
    gate_close_channel: 'int const'
    initial: 'GatedChannelInitial const'
    __swig_destroy__: Incomplete

CoincidenceTimestamp_Last: Incomplete
CoincidenceTimestamp_Average: Incomplete
CoincidenceTimestamp_First: Incomplete
CoincidenceTimestamp_ListedFirst: Incomplete

class Coincidences(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getChannels(self) -> 'std::vector< int,std::allocator< int > >': ...
    def setCoincidenceWindow(self, coincidenceWindow: 'long long') -> void: ...

class Coincidence(Coincidences):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def getChannel(self) -> int: ...
    __swig_destroy__: Incomplete

class Combinations(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, channels: _IntVector, window_size: 'long long') -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self, input_channels: _IntVector) -> int: ...
    def getChannels(self, list_of_input_channel_sets: _IntVectorVector) -> 'std::vector< int,std::allocator< int > >': ...
    def getChannelByMask(self, input_mask: uint32_t) -> int: ...
    def getCombination(self, virtual_channel: int) -> 'std::vector< int,std::allocator< int > >': ...
    def getSumChannel(self, n_channels: int) -> int: ...

class Combiner(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, channels: _IntVector) -> None: ...
    __swig_destroy__: Incomplete
    def getChannelCounts(self) -> void: ...
    def getData(self) -> void: ...
    def getChannel(self) -> int: ...

class ConditionalFilterChannel(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...
    def getChannels(self) -> 'std::vector< int,std::allocator< int > >': ...

class ConstantFractionDiscriminator(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, channels: _IntVector, search_window: 'long long') -> None: ...
    __swig_destroy__: Incomplete
    def getChannels(self) -> 'std::vector< int,std::allocator< int > >': ...

class Correlation(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> void: ...
    def getDataNormalized(self) -> void: ...
    def getIndex(self) -> void: ...

class CorrelationPairsData:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getCounts(self, exclude_self_coincidences: bool = True) -> void: ...
    def getG2(self, exclude_self_coincidences: bool = True) -> void: ...
    def getIndex(self) -> void: ...

class CorrelationPairs(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, channels: _IntVector, binwidth: 'long long' = 1000, n_bins: int = 1000) -> None: ...
    __swig_destroy__: Incomplete
    def getDataObject(self) -> CorrelationPairsData: ...
    def getIndex(self) -> void: ...

class CountBetweenMarkers(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> void: ...
    def getIndex(self) -> void: ...
    def getBinWidths(self) -> void: ...
    def ready(self) -> bool: ...

class CounterData:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getIndex(self) -> void: ...
    def getData(self) -> void: ...
    def getDataNormalized(self) -> void: ...
    def getFrequency(self, *args, **kwargs) -> void: ...
    def getDataTotalCounts(self) -> void: ...
    def getTime(self) -> void: ...
    def getOverflowMask(self) -> void: ...
    def getChannels(self) -> void: ...
    size: 'uint32_t const'
    dropped_bins: 'uint32_t const'
    overflow: 'bool const'
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...

class Counter(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, channels: _IntVector, binwidth: 'long long' = 1000000000, n_values: int32_t = 1) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self, rolling: bool = True) -> void: ...
    def getIndex(self) -> void: ...
    def getDataNormalized(self, rolling: bool = True) -> void: ...
    def getDataTotalCounts(self) -> void: ...
    def getDataObject(self, remove: bool = False) -> CounterData: ...

class Countrate(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, channels: _IntVector) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> void: ...
    def getCountsTotal(self) -> void: ...

class CustomMeasurementBase(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase) -> None: ...
    __swig_destroy__: Incomplete
    @staticmethod
    def stop_all_custom_measurements() -> void: ...
    def register_channel(self, channel: int) -> void: ...
    def unregister_channel(self, channel: int) -> void: ...
    def finalize_init(self) -> void: ...
    def is_running(self) -> bool: ...
    def next_impl(self, incoming_tags: 'std::vector< Tag,std::allocator< Tag > > &', begin_time: 'long long', end_time: 'long long') -> bool: ...
    def next_impl_cs(self, tags_ptr: 'void *', num_tags: uint64_t, begin_time: 'long long', end_time: 'long long') -> void: ...
    def clear_impl(self) -> void: ...
    def on_start(self) -> void: ...
    def on_stop(self) -> void: ...
    def pre_stop(self) -> void: ...
    def __disown__(self): ...

class DelayedChannels(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, input_channels: _IntVector, delay: 'long long') -> None: ...
    __swig_destroy__: Incomplete
    def getChannels(self) -> 'std::vector< int,std::allocator< int > >': ...
    def setDelay(self, delay: 'long long') -> void: ...

class DelayedChannel(DelayedChannels):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, input_channel: int, delay: 'long long') -> None: ...
    def getChannel(self) -> int: ...
    __swig_destroy__: Incomplete

class Dump(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete

class EventGenerator(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...

class FileReader:
    thisown: Incomplete
    def __init__(self, *args) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self, n_events: uint64_t) -> TimeTagStreamBuffer: ...
    def hasData(self) -> bool: ...
    def getConfiguration(self) -> 'std::string': ...
    def getChannelList(self) -> 'std::vector< int,std::allocator< int > >': ...
    def getLastMarker(self) -> 'std::string': ...
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...

class FileWriter(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, filename: 'std::string const &', channels: _IntVector) -> None: ...
    __swig_destroy__: Incomplete
    def split(self, *args, **kwargs) -> void: ...
    def setMaxFileSize(self, max_file_size: uint64_t) -> void: ...
    def getMaxFileSize(self) -> uint64_t: ...
    def getTotalEvents(self) -> uint64_t: ...
    def getTotalSize(self) -> uint64_t: ...
    def setMarker(self, marker: 'std::string const &') -> void: ...

class FlimAbstract(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def isAcquiring(self) -> bool: ...

class FlimBase(FlimAbstract):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def initialize(self) -> void: ...
    def frameReady(self, frame_number: uint32_t, data: _UIntVector, pixel_begin_times: _LongLongVector, pixel_end_times: _LongLongVector, frame_begin_time: 'long long', frame_end_time: 'long long') -> void: ...
    def __disown__(self): ...

class FlimFrameInfo:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getFrameNumber(self) -> int32_t: ...
    def isValid(self) -> bool: ...
    def getPixelPosition(self) -> uint32_t: ...
    def getHistograms(self) -> void: ...
    def getIntensities(self) -> void: ...
    def getSummedCounts(self) -> void: ...
    def getPixelBegins(self) -> void: ...
    def getPixelEnds(self) -> void: ...
    pixels: uint32_t
    bins: uint32_t
    frame_number: int32_t
    pixel_position: uint32_t
    valid: bool
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...

class Flim(FlimAbstract):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getCurrentFrame(self) -> void: ...
    def getCurrentFrameEx(self) -> FlimFrameInfo: ...
    def getCurrentFrameIntensity(self) -> void: ...
    def getFramesAcquired(self) -> uint32_t: ...
    def getIndex(self) -> void: ...
    def getReadyFrame(self, index: int32_t = -1) -> void: ...
    def getReadyFrameEx(self, index: int32_t = -1) -> FlimFrameInfo: ...
    def getReadyFrameIntensity(self, index: int32_t = -1) -> void: ...
    def getSummedFrames(self, only_ready_frames: bool = True, clear_summed: bool = False) -> void: ...
    def getSummedFramesEx(self, only_ready_frames: bool = True, clear_summed: bool = False) -> FlimFrameInfo: ...
    def getSummedFramesIntensity(self, only_ready_frames: bool = True, clear_summed: bool = False) -> void: ...
    def initialize(self) -> void: ...
    def frameReady(self, frame_number: uint32_t, data: _UIntVector, pixel_begin_times: _LongLongVector, pixel_end_times: _LongLongVector, frame_begin_time: 'long long', frame_end_time: 'long long') -> void: ...
    def __disown__(self): ...

class FrequencyCounterData:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getIndex(self) -> void: ...
    def getTime(self) -> void: ...
    def getPeriodsCount(self) -> void: ...
    def getPeriodsFraction(self) -> void: ...
    def getPhase(self, reference_frequency: double = 0) -> void: ...
    def getFrequency(self, *args, **kwargs) -> void: ...
    def getFrequencyInstantaneous(self) -> void: ...
    def getOverflowMask(self) -> void: ...
    size: 'unsigned int const'
    overflow_samples: 'long long const'
    align_to_reference: 'bool const'
    sampling_interval: 'long long const'
    sample_offset: 'long long const'
    channels_last_dim: 'bool const'
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...

class FrequencyCounter(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, channels: _IntVector, sampling_interval: 'long long', fitting_window: 'long long', n_values: int32_t = 0) -> None: ...
    __swig_destroy__: Incomplete
    def getDataObject(self, event_divider: uint16_t = 1, remove: bool = False, channels_last_dim: bool = False) -> FrequencyCounterData: ...

class FrequencyMultiplier(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, input_channel: int, multiplier: int32_t) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...
    def getMultiplier(self) -> int32_t: ...

class FrequencyStabilityData:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getTau(self) -> void: ...
    def getADEV(self) -> void: ...
    def getMDEV(self) -> void: ...
    def getHDEV(self) -> void: ...
    def getSTDD(self) -> void: ...
    def getADEVScaled(self) -> void: ...
    def getTDEV(self) -> void: ...
    def getHDEVScaled(self) -> void: ...
    def getTraceIndex(self) -> void: ...
    def getTracePhase(self) -> void: ...
    def getTraceFrequency(self) -> void: ...
    def getTraceFrequencyAbsolute(self, input_frequency: double = 0.0) -> void: ...
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...

class FrequencyStability(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, channel: int, steps: _ULongVector, average: 'long long' = 1000, trace_len: uint64_t = 1000) -> None: ...
    __swig_destroy__: Incomplete
    def getDataObject(self) -> FrequencyStabilityData: ...

class GatedChannel(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...

GatedChannelInitial_Closed: Incomplete
GatedChannelInitial_Open: Incomplete

class HistogramLogBinsData:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getG2(self) -> void: ...
    def getCounts(self) -> void: ...
    def getG2Normalization(self) -> void: ...
    accumulation_time_start: 'long long const'
    accumulation_time_click: 'long long const'
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...

class HistogramLogBins(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, click_channel: int, start_channel: int, exp_start: double, exp_stop: double, n_bins: int32_t, click_gate: ChannelGate = None, start_gate: ChannelGate = None) -> None: ...
    __swig_destroy__: Incomplete
    def getDataObject(self) -> HistogramLogBinsData: ...
    def getBinEdges(self) -> void: ...
    def getData(self) -> void: ...
    def getDataNormalizedCountsPerPs(self) -> void: ...
    def getDataNormalizedG2(self) -> void: ...

class HistogramCustomBins(HistogramLogBins):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, click_channel: int, start_channel: int, binedges: _LongLongVector, click_gate: ChannelGate = None, start_gate: ChannelGate = None) -> None: ...
    __swig_destroy__: Incomplete

class Histogram2D(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, start_channel: int, stop_channel_1: int, stop_channel_2: int, binwidth_1: 'long long', binwidth_2: 'long long', n_bins_1: int32_t, n_bins_2: int32_t) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> void: ...
    def getIndex(self) -> void: ...
    def getIndex_1(self) -> void: ...
    def getIndex_2(self) -> void: ...

class HistogramND(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, start_channel: int, stop_channels: _IntVector, binwidths: _LongLongVector, n_bins: _IntVector) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> void: ...
    def getIndex(self, dim: int32_t = 0) -> void: ...

class Iterator(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, channel: int) -> None: ...
    __swig_destroy__: Incomplete
    def next(self) -> 'long long': ...
    def size(self) -> uint64_t: ...

class Experimental_MarkovProcessGenerator(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...
    def getChannels(self) -> 'std::vector< int,std::allocator< int > >': ...

class OverflowInjector(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, delay: 'long long', length: 'long long') -> None: ...
    __swig_destroy__: Incomplete

class PhaseNoiseData:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getPhaseNoise(self) -> void: ...
    def getIntegratedJitter(self, lower_bound: double = 12000.0, upper_bound: double = -1.0) -> double: ...
    def getOffset(self) -> void: ...
    def getAveragedSequences(self) -> void: ...
    def getFrequency(self) -> double: ...
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...

class PhaseNoise(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, channel: int, samples_per_octave: int = 32) -> None: ...
    __swig_destroy__: Incomplete
    def getDataObject(self) -> PhaseNoiseData: ...

class Experimental_PhotonNumber(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, trigger_ch: int, signal_start_ch: int, signal_stop_ch: int, slope: double, x_intercepts: _DoubleVector, dead_time: 'long long') -> None: ...
    __swig_destroy__: Incomplete
    def getChannels(self) -> 'std::vector< int,std::allocator< int > > const &': ...

class Experimental_PulsePerSecondData:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def getIndices(self) -> void: ...
    def getReferenceOffsets(self) -> void: ...
    def getSignalOffsets(self) -> void: ...
    def getUtcSeconds(self) -> void: ...
    def getUtcDates(self) -> 'std::vector< std::string,std::allocator< std::string > >': ...
    def getStatus(self) -> void: ...
    size: 'size_t const'
    __swig_destroy__: Incomplete
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...

class Experimental_PulsePerSecondMonitor(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getDataObject(self, remove: bool = False) -> 'Experimental::PulsePerSecondData': ...

class Sampler(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, trigger: int, channels: _IntVector, max_triggers: size_t) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> void: ...
    def getDataAsMask(self) -> void: ...

UNKNOWN: Incomplete
HIGH: Incomplete
LOW: Incomplete

class Event:
    thisown: Incomplete
    time: 'long long'
    state: State
    def __init__(self) -> None: ...
    __swig_destroy__: Incomplete

class Scope(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, event_channels: _IntVector, trigger_channel: int, window_size: 'long long' = 1000000000, n_traces: int32_t = 1, n_max_events: int32_t = 1000) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> 'std::vector< std::vector< Event,std::allocator< Event > >,std::allocator< std::vector< Event,std::allocator< Event > > > >': ...
    def ready(self) -> bool: ...
    def triggered(self) -> int32_t: ...
    def getWindowSize(self) -> 'long long': ...

class Experimental_SignalGeneratorBase(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...

class Experimental_PhotonGenerator(Experimental_SignalGeneratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, countrate: double, base_channel: int, seed: int32_t = -1) -> None: ...
    __swig_destroy__: Incomplete
    def finalize_init(self) -> void: ...
    def set_T_PERIOD(self, new_T: 'long long') -> void: ...
    def get_T_PERIOD(self) -> 'long long': ...
    def initialize(self, initial_time: 'long long') -> void: ...
    def on_restart(self, restart_time: 'long long') -> void: ...
    def get_next(self) -> 'long long': ...
    def get_intensity(self) -> double: ...
    def __disown__(self): ...
    def clear_impl(self) -> void: ...
    def on_start(self) -> void: ...
    def on_stop(self) -> void: ...
    def pre_stop(self) -> void: ...
    def next_impl(self, incoming_tags: 'std::vector< Tag,std::allocator< Tag > > &', begin_time: 'long long', end_time: 'long long') -> bool: ...

class Experimental_DlsSignalGenerator(Experimental_PhotonGenerator):
    thisown: Incomplete
    def __init__(self, *args) -> None: ...
    __swig_destroy__: Incomplete
    def get_N(self) -> 'unsigned int': ...

class Experimental_FcsSignalGenerator(Experimental_PhotonGenerator):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def get_N(self) -> 'unsigned int': ...
    def set_boundary_limit(self, new_boundary: double) -> void: ...

class Experimental_UniformSignalGenerator(Experimental_SignalGeneratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete

class Experimental_GaussianSignalGenerator(Experimental_SignalGeneratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete

class Experimental_OscillatorSimulation(Experimental_SignalGeneratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete

class Experimental_TwoStateExponentialSignalGenerator(Experimental_SignalGeneratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete

class Experimental_ExponentialSignalGenerator(Experimental_SignalGeneratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete

class Experimental_GammaSignalGenerator(Experimental_SignalGeneratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete

class Experimental_PatternSignalGenerator(Experimental_SignalGeneratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete

class Experimental_SimSignalSplitter(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, input_channel: int, ratio: double = 0.5, seed: int32_t = -1) -> None: ...
    __swig_destroy__: Incomplete
    def getChannels(self) -> 'std::vector< int,std::allocator< int > >': ...
    def getLeftChannel(self) -> int: ...
    def getRightChannel(self) -> int: ...

class Experimental_TransformEfficiency(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, input_channel: int, efficiency: double, copy: bool = False, seed: int32_t = -1) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...

class Experimental_TransformGaussianBroadening(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, input_channel: int, standard_deviation: double, copy: bool = False, seed: int32_t = -1) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...

class Experimental_TransformDeadtime(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, input_channel: int, deadtime: double, copy: bool = False) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...

class Experimental_TransformCrosstalk(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, input_channel: int, relay_input_channel: int, delay: double, tau: double, copy: bool = False) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...

class Experimental_SimDetector:
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, input_channel: int, efficiency: double = 1.0, darkcount_rate: double = 0.0, jitter: double = 0, deadtime: double = 0.0, seed: int32_t = -1) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...

class Experimental_SimLifetime(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, input_channel: int, lifetime: double, emission_rate: double = 0.1, seed: int32_t = -1) -> None: ...
    __swig_destroy__: Incomplete
    def getChannel(self) -> int: ...
    def registerLifetimeReactor(self, trigger_channel: int, lifetimes: _DoubleVector, repeat: bool) -> void: ...
    def registerEmissionReactor(self, trigger_channel: int, emissions: _DoubleVector, repeat: bool) -> void: ...

class StartStop(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> void: ...

class SynchronizedMeasurements:
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase) -> None: ...
    __swig_destroy__: Incomplete
    def getTagger(self) -> 'TimeTaggerBase *': ...
    def start(self) -> void: ...
    def startFor(self, capture_duration: 'long long', clear: bool = True) -> void: ...
    def stop(self) -> void: ...
    def clear(self) -> void: ...
    def isRunning(self) -> bool: ...
    def registerMeasurement(self, measurement: IteratorBase) -> void: ...
    def unregisterMeasurement(self, measurement: IteratorBase) -> void: ...
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...
    def waitUntilFinished(self, timeout: int = -1): ...

class SyntheticSingleTag(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def trigger(self) -> void: ...
    def getChannel(self) -> int: ...

class TimeDifferences(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> void: ...
    def getIndex(self) -> void: ...
    def setMaxCounts(self, max_counts: uint64_t) -> void: ...
    def setMaxRollovers(self, max_rollovers: uint64_t) -> void: ...
    def getHistogramIndex(self) -> int32_t: ...
    def getCounts(self) -> uint64_t: ...
    def ready(self) -> bool: ...

class Histogram(IteratorBase):
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> void: ...
    def getIndex(self) -> void: ...

class TimeDifferencesND(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, click_channel: int, start_channel: int, next_channels: _IntVector, sync_channels: _IntVector, n_histograms: _IntVector, binwidth: 'long long', n_bins: int32_t) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> void: ...
    def getIndex(self) -> void: ...
    def setMaxRollovers(self, max_rollovers: _ULongVector) -> void: ...
    def getHistogramIndex(self) -> void: ...
    def getRollovers(self) -> void: ...

class TimeTagStream(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, n_max_events: uint64_t, channels: _IntVector) -> None: ...
    __swig_destroy__: Incomplete
    def getData(self) -> TimeTagStreamBuffer: ...
    def getCounts(self) -> uint64_t: ...

class TimeTagStreamBuffer:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __swig_destroy__: Incomplete
    def getTimestamps(self) -> void: ...
    def getChannels(self) -> void: ...
    def getOverflows(self) -> void: ...
    def getEventTypes(self) -> void: ...
    def getMissedEvents(self) -> void: ...
    size: uint64_t
    hasOverflows: bool
    tStart: 'long long'
    tGetData: 'long long'
    def __enter__(self): ...
    this: Incomplete
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None): ...

class TriggerOnCountrate(IteratorBase):
    thisown: Incomplete
    def __init__(self, tagger: TimeTaggerBase, input_channel: int, reference_countrate: double, hysteresis: double, time_window: 'long long') -> None: ...
    __swig_destroy__: Incomplete
    def getChannelAbove(self) -> int: ...
    def getChannelBelow(self) -> int: ...
    def getChannels(self) -> 'std::vector< int,std::allocator< int > >': ...
    def getCurrentCountrate(self) -> double: ...
    def injectCurrentState(self) -> bool: ...
    def isAbove(self) -> bool: ...
    def isBelow(self) -> bool: ...

class CustomMeasurement(CustomMeasurementBase):
    INCOMING_TAGS_DTYPE: Incomplete
    showError: bool
    iter: Incomplete
    mutex: Incomplete
    def __init__(self, time_tagger) -> None: ...
    def stop(self, *args, **kwargs) -> None: ...
    def __exit__(self, *args, **kwargs): ...
    def process(self, incoming_tags, begin_time, end_time) -> None: ...
    def next_impl_cs(self, incoming_tags, begin_time, end_time): ...

def setLogger(callback) -> None: ...
def freeTimeTagger(tagger: TimeTaggerBase) -> None: ...

class Experimental: ...

expt_classes: Incomplete

class CoincidenceTimestamp(_enum.IntEnum):
    Last = CoincidenceTimestamp_Last
    Average = CoincidenceTimestamp_Average
    First = CoincidenceTimestamp_First
    ListedFirst = CoincidenceTimestamp_ListedFirst

class Resolution(_enum.IntEnum):
    Standard = Resolution_Standard
    HighResA = Resolution_HighResA
    HighResB = Resolution_HighResB
    HighResC = Resolution_HighResC

class ChannelEdge(_enum.IntFlag):
    All = ChannelEdge_All
    Rising = ChannelEdge_Rising
    Falling = ChannelEdge_Falling
    HighResAll = ChannelEdge_HighResAll
    HighResRising = ChannelEdge_HighResRising
    HighResFalling = ChannelEdge_HighResFalling
    StandardAll = ChannelEdge_StandardAll
    StandardRising = ChannelEdge_StandardRising
    StandardFalling = ChannelEdge_StandardFalling

class UsageStatisticsStatus(_enum.IntEnum):
    Disabled = UsageStatisticsStatus_Disabled
    Collecting = UsageStatisticsStatus_Collecting
    CollectingAndUploading = UsageStatisticsStatus_CollectingAndUploading

class FrontendType(_enum.IntEnum):
    Undefined = FrontendType_Undefined
    WebApp = FrontendType_WebApp
    Firefly = FrontendType_Firefly
    Pyro5RPC = FrontendType_Pyro5RPC
    UserFrontend = FrontendType_UserFrontend

class LanguageUsed(_enum.IntEnum):
    Cpp = LanguageUsed_Cpp
    Python = LanguageUsed_Python
    Csharp = LanguageUsed_Csharp
    Matlab = LanguageUsed_Matlab
    Labview = LanguageUsed_Labview
    Mathematica = LanguageUsed_Mathematica
    Unknown = LanguageUsed_Unknown

class AccessMode(_enum.IntFlag):
    Listen = AccessMode_Listen
    SynchronousListen = AccessMode_SynchronousListen
    Control = AccessMode_Control
    SynchronousControl = AccessMode_SynchronousControl

class TagType(_enum.IntEnum):
    TimeTag = ...
    Error = ...
    OverflowBegin = ...
    OverflowEnd = ...
    MissedEvents = ...

class GatedChannelInitial(_enum.IntEnum):
    Closed = GatedChannelInitial_Closed
    Open = GatedChannelInitial_Open

class FpgaLinkInterface(_enum.IntEnum):
    SFPP_10GE = FpgaLinkInterface_SFPP_10GE
    QSFPP_40GE = FpgaLinkInterface_QSFPP_40GE
