import argparse
import json
from pathlib import Path


def _load_schema(path: str) -> dict:
    return json.loads(Path(path).read_text())


def _all_class_names(schema: dict) -> set[str]:
    """Every class that becomes a handle on the wire."""
    return set(schema['classes'].keys()) | set(schema['abstract_bases'].keys())


def _is_handle_param(param: dict, handle_classes: set[str]) -> bool:
    """True if this param carries a server-side object handle."""
    return param.get('_raw_pyi') in handle_classes


def _is_ndarray_return(method: dict) -> bool:
    ret = method.get('returns', {})
    return ret.get('$ref') == '#/$defs/ndarray'


def _is_handle_return(method: dict) -> bool:
    ret = method.get('returns', {})
    return ret.get('$ref') == '#/$defs/handle' and 'returns_class' in ret


def _return_class(method: dict) -> str | None:
    return method.get('returns', {}).get('returns_class')


def _is_data_object(class_name: str, cls: dict) -> bool:
    _ = class_name  # TODO: might need this later, not sure yet
    """DataObject classes are identified by having a discard() method."""
    return 'discard' in cls.get('methods', {})


def _collect_methods(class_name: str, schema: dict) -> dict:
    """
    Return the full flattened method set for a class, merging in all
    ancestor methods from abstract_bases in MRO order.
    The class's own methods take priority over inherited ones.
    """
    cls = schema['classes'][class_name]
    inherited_names = cls.get('inherits', [])
    if isinstance(inherited_names, str):
        inherited_names = [inherited_names]

    merged = {}
    # Walk bases first (depth-first), then apply own methods on top
    for base in inherited_names:
        merged.update(_collect_abstract_methods(base, schema))
    merged.update(cls.get('methods', {}))
    return merged


def _collect_abstract_methods(base_name: str, schema: dict) -> dict:
    """Recursively collect methods from abstract_bases, respecting their own inheritance."""
    bases_section = schema['abstract_bases']
    if base_name not in bases_section:
        return {}
    base = bases_section[base_name]
    parent = base.get('inherits')
    result = {}
    if parent:
        parents = [parent] if isinstance(parent, str) else parent
        for p in parents:
            result.update(_collect_abstract_methods(p, schema))
    result.update(base.get('methods', {}))
    return result


def _repr_default(val) -> str:
    """Python literal for a default value."""
    if val is None:
        return 'None'
    if isinstance(val, bool):
        return 'True' if val else 'False'
    if isinstance(val, str):
        return repr(val)
    return str(val)


SERVER_HEADER = '''\
"""
server_handlers.py — AUTO-GENERATED by codegen.py. Do not edit directly.
Re-generate by running: python codegen.py schema.json --out-dir <dir>

Contains:
  HANDLERS  dict[str, Callable] mapping "ClassName.method" → handler fn
  Each handler signature: fn(session_id, registry, params) -> result
"""

from __future__ import annotations
import sys
from typing import TYPE_CHECKING, Any, Callable
from functools import wraps
from dataclasses import dataclass
import numpy as np

try:
    from Swabian import TimeTagger as TT
except ImportError:
    import TimeTagger as TT


@dataclass
class HandlerContext:
    session_id: int
    registry: dict
    sessions: dict


if TYPE_CHECKING:
    if sys.version_info >= (3, 12):
        type SwabianFn = Callable[[HandlerContext, Any], Any]
    else:
        from typing import TypeAlias
        SwabianFn: TypeAlias = Callable[[HandlerContext, Any], Any]

HANDLERS: dict[str, SwabianFn] = {}

def handler(name: str):
    def decorator(func: SwabianFn):
        @wraps(func)
        def wrapper(*args: Any, **kwargs: Any) -> Any:
            return func(*args, **kwargs)

        HANDLERS[name] = wrapper
        return wrapper
    return decorator


def _lookup(registry: dict, handle_id: int):
    entry = registry.get(handle_id)
    if entry is None:
        raise KeyError(f"Unknown handle: {handle_id}")
    return entry["obj"]

def _register(obj, class_name: str, session_id: int, registry: dict, sessions: dict) -> int:
    import itertools
    handle_id = next(registry["_counter"])
    registry[handle_id] = {"obj": obj, "class_name": class_name,
                           "session_id": session_id}
    sessions.setdefault(session_id, set()).add(handle_id)
    return handle_id

# numpy array needs to be marshalled
def _pack_ndarray(arr) -> dict:
    import io
    buf = io.BytesIO()
    np.save(buf, arr, allow_pickle=False)
    return {"dtype": str(arr.dtype),
            "shape": list(arr.shape),
            "data": buf.getvalue()}

'''


class ServerGenerator:
    def __init__(self, schema: dict):
        self.schema = schema
        self.handle_classes = _all_class_names(schema)
        # self.constructor_fns = schema.get("functions", {})
        self._ctor_fn: dict[str, str] = {}
        for fn_name, fn in schema['functions'].items():
            rc = fn.get('returns', {}).get('returns_class')
            if rc:
                self._ctor_fn[rc] = fn_name

    def generate(self) -> str:
        lines = [SERVER_HEADER]
        lines += self._gen_module_functions()
        lines += self._gen_class_constructors()
        lines += self._gen_class_methods()
        return '\n'.join(lines)

    def _gen_module_functions(self) -> list[str]:
        lines = [
            '# Module-level functions',
            '',
        ]
        for fn_name, fn in self.schema['functions'].items():
            if fn_name.startswith('_'):
                continue
            lines += self._fn_handler(fn_name, fn)
            lines.append('')
        return lines

    def _fn_handler(self, fn_name: str, fn: dict) -> list[str]:
        ret_class = fn.get('returns', {}).get('returns_class')
        is_ndarray = _is_ndarray_return(fn)
        variadic = fn.get('params_variable', False)

        lines = [
            f'@handler("{fn_name}")',
            f'def _fn_{fn_name}(ctx: HandlerContext, params):',
        ]

        if variadic:
            call = f'TT.{fn_name}(*params)'
        else:
            params = fn.get('params', [])
            args = self._server_args(params, offset=0)
            if len(args) == 0:
                lines.append('    _ = params')
            call = f'TT.{fn_name}({args})'

        if ret_class:
            lines.append(f'    obj = {call}')
            lines.append(
                f'    return _register(obj, {ret_class!r}, ctx.session_id, ctx.registry, ctx.sessions)'
            )
        elif is_ndarray:
            lines.append(f'    return _pack_ndarray({call})')
        else:
            lines.append('    _ = ctx')
            lines.append(f'    return {call}')

        return lines

    def _gen_class_constructors(self) -> list[str]:
        lines = [
            '# Class constructors',
            '',
        ]
        for class_name, cls in self.schema['classes'].items():
            ctor = cls.get('constructor')
            if ctor is None:
                continue
            # Skip classes that have a dedicated module-level factory function
            # (those are already emitted in _gen_module_functions)
            if class_name in self._ctor_fn:
                continue
            lines += self._ctor_handler(class_name, ctor)
            lines.append('')
        return lines

    def _ctor_handler(self, class_name: str, ctor: dict) -> list[str]:
        variadic = ctor.get('params_variable', False)
        params = ctor.get('params', [])

        lines = [
            f'@handler("{class_name}")',
            f'def _ctor_{class_name}(ctx: HandlerContext, params):',
        ]

        if variadic:
            # Resolve first param if it's a handle, splat the rest
            lines.append(f'    obj = TT.{class_name}(*params)')
        else:
            args = self._server_args(params, offset=0)
            lines.append(f'    obj = TT.{class_name}({args})')

        lines.append(
            f'    return _register(obj, {class_name!r}, ctx.session_id, ctx.registry, ctx.sessions)'
        )
        return lines

    def _gen_class_methods(self) -> list[str]:
        lines = [
            '# Instance methods',
            '',
        ]
        for class_name in self.schema['classes']:
            all_methods = _collect_methods(class_name, self.schema)
            for method_name, method in all_methods.items():
                lines += self._method_handler(class_name, method_name, method)
                lines.append('')
        return lines

    def _method_handler(
        self, class_name: str, method_name: str, method: dict
    ) -> list[str]:
        fn = f'_m_{class_name}_{method_name}'
        ret_class = _return_class(method)
        is_ndarray = _is_ndarray_return(method)
        is_handle = _is_handle_return(method)
        variadic = method.get('params_variable', False)
        params = method.get('params', [])

        lines = [
            f'@handler("{class_name}.{method_name}")',
            f'def {fn}(ctx: HandlerContext, params):',
        ]
        lines.append('    obj = _lookup(ctx.registry, params[0])')

        if variadic:
            call = f'obj.{method_name}(*params[1:])'
        else:
            args = self._server_args(params, offset=1)
            call = f'obj.{method_name}({args})'

        if is_handle:
            lines.append(f'    result = {call}')
            lines.append(
                f'    return _register(result, {ret_class!r}, ctx.session_id, ctx.registry, ctx.sessions)'
            )
        elif is_ndarray:
            lines.append(f'    return _pack_ndarray({call})')
        else:
            lines.append(f'    return {call}')

        return lines

    def _server_args(self, params: list, offset: int) -> str:
        """Build the argument string for a TT call from params[offset:]."""
        parts = []
        for i, p in enumerate(params):
            idx = i + offset
            if _is_handle_param(p, self.handle_classes):
                parts.append(f'_lookup(ctx.registry, params[{idx}])')
            else:
                parts.append(f'params[{idx}]')
        return ', '.join(parts)


CLIENT_HEADER = '''\
"""
client_stubs.py — AUTO-GENERATED by codegen.py. Do not edit directly.
Re-generate by running: python codegen.py schema.json --out-dir <dir>

Drop-in replacement for the TimeTagger Python library for remote use.

Usage:
    from swamptt import Session as TT

    tt     = TT.connect("192.168.1.10")          # one connection to the RPC server
    tagger = tt.createTimeTagger()               # hardware via the session
    ctr    = tt.Counter(tagger, [1, 2],          # ALL constructors live on the session —
                        binwidth=1_000_000_000)  # the _rpc connection is injected for you
    fr     = tt.FileReader("data.ttbin")         # works for classes with no tagger too
    data   = ctr.getData()
    print(tt.getVersion())                       # utility functions via the session
"""

from __future__ import annotations

import io
import itertools
import socket
from collections.abc import Callable
from functools import wraps
from typing import Concatenate, ParamSpec, TypeVar

import msgpack
import numpy as np

# Transport

class _Connection:
    def __init__(self, host: str, port: int):
        self._sock = socket.create_connection((host, port))
        self._sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
        self._unpacker = msgpack.Unpacker(raw=False)
        self._msgid = itertools.count(1)

    def request(self, method: str, params: list):
        msgid = next(self._msgid)
        self._sock.sendall(msgpack.packb([0, msgid, method, params], use_bin_type=True))
        while True:
            self._unpacker.feed(self._sock.recv(65536))
            for msg in self._unpacker:
                _, resp_id, error, result = msg
                if resp_id == msgid:
                    if error:
                        raise RuntimeError(error)
                    return result

    def close(self):
        self._sock.close()

_active_connection: _Connection | None = None

def connect(host: str = 'localhost', port: int = 9000) -> _Connection:
    global _active_connection
    _active_connection = _Connection(host, port)
    return _active_connection

def get_connection() -> _Connection:
    if _active_connection is None:
        raise RuntimeError("No active connection, call connect first")

    return _active_connection

# wrap classes with a decorator to inject the rpc connection, this way we can
# have the module look the same to the user as the actual swabian timetagger
# library
def remote(cls):
    original_init = cls.__init__

    @wraps(original_init)
    def __init__(self, *args, **kwargs):
        self._rpc = get_connection()
        original_init(self, *args, **kwargs)

    cls.__init__ = __init__
    return cls

P = ParamSpec('P')
R = TypeVar('R')

# let's wrap the module level functions in the same way, now we can do things
# like 'TT.getVersion()' just like we would with the *real* library
def remote_fn[**P, R](fn: Callable[Concatenate[_Connection, P], R]) -> Callable[P, R]:
    @wraps(fn)
    def wrapper(*args: P.args, **kwargs: P.kwargs) -> R:
        rpc = get_connection()
        return fn(rpc, *args, **kwargs)
    return wrapper


# numpy array needs marshalling
def _pack_ndarray(arr: np.ndarray) -> dict:
    buf = io.BytesIO()
    np.save(buf, arr, allow_pickle=False)
    return {"dtype": str(arr.dtype), "shape": list(arr.shape), "data": buf.getvalue()}

# as well for unpacking
def _unpack_ndarray(d: dict) -> np.ndarray:
    buf = io.BytesIO(d["data"] if isinstance(d["data"], bytes)
                     else d["data"].encode("latin-1"))
    return np.load(buf, allow_pickle=False)


'''


class ClientGenerator:
    def __init__(self, schema: dict):
        self.schema = schema
        self.handle_classes = _all_class_names(schema)
        # Map factory function name → class name
        self._factory_to_class: dict[str, str] = {}
        for fn_name, fn in schema['functions'].items():
            rc = fn.get('returns', {}).get('returns_class')
            if rc:
                self._factory_to_class[fn_name] = rc
        # Classes returned directly by factory functions (tagger types).
        # These get the same (__init__(self, _rpc, _handle)) style as DataObjects
        # because the user never constructs them directly — Session does.
        self._factory_returned: set[str] = set(self._factory_to_class.values())

    def generate(self) -> str:
        lines = [CLIENT_HEADER]
        lines += self._gen_classes()
        lines += self._gen_session()
        return '\n'.join(lines)

    def _gen_classes(self) -> list[str]:
        lines = [
            '# Stub classes',
            '',
        ]
        for class_name, cls in self.schema['classes'].items():
            lines += self._gen_class(class_name, cls)
            lines.append('')
        return lines

    def _gen_class(self, class_name: str, cls: dict) -> list[str]:
        is_data_obj = _is_data_object(class_name, cls)
        is_factory_returned = class_name in self._factory_returned
        all_methods = _collect_methods(class_name, self.schema)

        lines = [
            '@remote',
            f'class {class_name}:',
            '',
            '    _rpc: _Connection # this is injected by the @remote decorator',
            '',
        ]

        if is_data_obj or is_factory_returned:
            lines += self._gen_data_obj_init(class_name)
        else:
            lines += self._gen_user_init(class_name, cls)

        lines.append('')

        # methods
        for method_name, method in all_methods.items():
            lines += self._gen_method(class_name, method_name, method)
            lines.append('')

        return lines

    def _gen_data_obj_init(self, class_name: str) -> list[str]:
        return [
            '    """Server-side data object. Obtained via getDataObject() / getData()."""',
            '    def __init__(self, _handle: int):',
            '        self._handle = _handle',
        ]

    def _gen_user_init(self, class_name: str, cls: dict) -> list[str]:
        ctor = cls.get('constructor')
        if ctor is None:
            # No constructor in schema — internal/abstract class
            return [
                '    def __init__(self,_handle: int):',
                '        self._handle = _handle',
            ]

        # constructor may be a string reference to a factory fn (e.g. "createTimeTagger")
        if isinstance(ctor, str):
            ctor = {}

        factory_fn = next(
            (fn for fn, c in self._factory_to_class.items() if c == class_name),
            None,
        )
        method_key = factory_fn if factory_fn else class_name

        if ctor.get('params_variable'):
            # Use getattr(a, '_handle', a) so handle objects are unwrapped to their
            # integer handles while plain values (strings, ints, etc.) pass through
            # unchanged — no inheritance traversal needed.
            return [
                '    def __init__(self,  *args):',
                f'        self._handle = self._rpc.request({method_key!r},',
                "                            [getattr(a, '_handle', a) for a in args])",
            ]

        params = ctor.get('params', [])
        py_params, rpc_args = self._client_params_and_args(params)
        sig_params = ', '.join(['self', '_rpc: _Connection'] + py_params)

        # _rpc is always passed explicitly — no need to extract from a handle param.
        return [
            f'    def __init__({sig_params}):',
            f'        self._handle = self._rpc.request({method_key!r}, [{rpc_args}])',
        ]

    def _gen_method(
        self, class_name: str, method_name: str, method: dict
    ) -> list[str]:
        variadic = method.get('params_variable', False)
        params = method.get('params', [])
        ret_class = _return_class(method)
        is_ndarray = _is_ndarray_return(method)
        is_null = method.get('returns', {}).get('type') == 'null'
        rpc_key = f'{class_name}.{method_name}'

        ret_sig = ''
        if ret_class is not None:
            ret_sig = f' -> {ret_class}'

        if variadic:
            sig = f'    def {method_name}(self, *args){ret_sig}:'
            rpc_args = '[self._handle, *args]'
        else:
            py_params, rpc_args_str = self._client_params_and_args(params)
            sig_params = ', '.join(['self'] + py_params)
            sig = f'    def {method_name}({sig_params}){ret_sig}:'
            rpc_args = (
                f'[self._handle, {rpc_args_str}]'
                if rpc_args_str
                else '[self._handle]'
            )

        call = f'self._rpc.request({rpc_key!r}, {rpc_args})'

        lines = [sig]
        if ret_class:
            if ret_class.endswith('[]'):
                inner = ret_class[:-2]
                lines.append(f'        handles = {call}')
                lines.append(
                    f'        return [{inner}(self._rpc, h) for h in handles]'
                )
            else:
                lines.append(f'        handle = {call}')
                lines.append(f'        return {ret_class}(handle)')
        elif is_ndarray:
            lines.append(f'        return _unpack_ndarray({call})')
        elif is_null:
            lines.append(f'        {call}')
        else:
            lines.append(f'        return {call}')

        return lines

    def _gen_session(self) -> list[str]:
        lines = []
        for fn_name, fn in self.schema['functions'].items():
            if fn_name.startswith('_'):
                continue
            lines += self._gen_session_method(fn_name, fn)
            lines.append('')

        return lines


    def _gen_session_method(self, fn_name: str, fn: dict) -> list[str]:
        ret_class = fn.get('returns', {}).get('returns_class')
        is_ndarray = _is_ndarray_return(fn)
        is_null = fn.get('returns', {}).get('type') == 'null'
        variadic = fn.get('params_variable', False)
        is_factory = (
            ret_class is not None and ret_class in self.schema['classes']
        )

        ret_sig = ''
        if ret_class is not None:
            ret_sig = f' -> {ret_class}'

        if variadic:
            sig = f'def {fn_name}(_rpc: _Connection, *args){ret_sig}:'
            if is_factory:
                # createTimeTagger(*args) → TimeTagger(self._rpc, handle)
                return [
                    '@remote_fn',
                    sig,
                    f'    handle = _rpc.request({fn_name!r}, list(args))',
                    f'    return {ret_class}(handle)',
                ]
            call = f'_rpc.request({fn_name!r}, list(args))'
        else:
            params = fn.get('params', [])
            py_params, rpc_args = self._client_params_and_args(params)
            sig = (
                f'def {fn_name}(_rpc: _Connection, {", ".join(py_params)}){ret_sig}:'
                if py_params
                else f'def {fn_name}(_rpc: _Connection){ret_sig}:'
            )
            rpc_list = f'[{rpc_args}]' if rpc_args else '[]'
            if is_factory:
                return [
                    '@remote_fn',
                    sig,
                    f'    handle = _rpc.request({fn_name!r}, {rpc_list})',
                    f'    return {ret_class}(handle)',
                ]
            call = f'_rpc.request({fn_name!r}, {rpc_list})'

        if is_ndarray:
            return [
                '@remote_fn',
                sig,
                f'    return _unpack_ndarray({call})',
            ]
        if is_null:
            return [
                '@remote_fn',
                sig,
                f'    {call}',
            ]
        return [
            '@remote_fn',
            sig,
            f'    return {call}',
        ]

    def _client_params_and_args(self, params: list) -> tuple[list[str], str]:
        """
        Returns:
          py_params  - list of 'name' or 'name=default' strings for the def signature
          rpc_args   - comma-joined string of expressions to put in the params list
        """
        py_params = []
        rpc_parts = []

        for p in params:
            name = p['name']
            has_default = 'default' in p
            default_val = (
                _repr_default(p.get('default')) if has_default else None
            )

            if _is_handle_param(p, self.handle_classes):
                py_params.append(
                    f'{name}={default_val}' if has_default else name
                )
                rpc_parts.append(f'{name}._handle')
            else:
                py_params.append(
                    f'{name}={default_val}' if has_default else name
                )
                rpc_parts.append(name)

        return py_params, ', '.join(rpc_parts)


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('schema', help='Path to generated schema JSON')
    parser.add_argument(
        '--out-dir', default='.', help='Output directory (default: .)'
    )
    args = parser.parse_args()

    schema = _load_schema(args.schema)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    server_src = ServerGenerator(schema).generate()
    client_src = ClientGenerator(schema).generate()

    server_path = out_dir / 'server_handlers.py'
    client_path = out_dir / 'client_stubs.py'

    server_path.write_text(server_src)
    client_path.write_text(client_src)

    print(f'Written: {server_path}')
    print(f'Written: {client_path}')


if __name__ == '__main__':
    main()
